apiVersion: apps/v1
kind: Deployment
metadata:
  name: ado-iac-agent-deployment
  namespace: ado-agents
spec:
  replicas: 0  # KEDA will manage replicas
  selector:
    matchLabels:
      app: ado-iac-agent
  template:
    metadata:
      labels:
        app: ado-iac-agent
    spec:
      serviceAccountName: ado-agent-iac
      automountServiceAccountToken: false
      containers:
      - name: ado-iac-agent
        image: 742846647113.dkr.ecr.us-west-2.amazonaws.com/ado-agent-cluster-iac-agents:latest
        env:
        - name: AZP_ORG
          valueFrom:
            secretKeyRef:
              name: ado-agent-pat
              key: organization
        - name: AZP_URL
          valueFrom:
            secretKeyRef:
              name: ado-agent-pat
              key: adourl
        - name: AZP_TOKEN
          valueFrom:
            secretKeyRef:
              name: ado-agent-pat
              key: personalAccessToken
        - name: AZP_POOL
          value: "batch-poc-eks-agent-iac-pool"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      restartPolicy: Always