apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-devops-trigger
  namespace: ado-agents
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: ado-agent-pat
      key: personalAccessToken