# ServiceAccount for dev-build workloads
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ado-agent-dev-build
  namespace: ado-agents
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::742846647113:role/ado-agent-cluster-ado-agent-dev-build-role"
---
# ServiceAccount for iac workloads
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ado-agent-iac
  namespace: ado-agents
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::742846647113:role/ado-agent-cluster-ado-agent-iac-role"