# =============================================================================
# Networking Layer Terragrunt Configuration
# =============================================================================
# This layer installs optional Kubernetes CNI components after the base EKS
# cluster exists and before middleware/application workloads are deployed.

include "root" {
  path = find_in_parent_folders("root.hcl")
}

include "common" {
  path = find_in_parent_folders("common.hcl")
}

terraform {
  source = "."

  before_hook "check_base_dependency" {
    commands = ["apply", "plan"]
    execute  = ["echo", "Networking layer depends on base layer outputs..."]
  }

  after_hook "networking_deployed" {
    commands     = ["apply"]
    execute      = ["bash", "-c", "echo 'Networking layer deployed.'"]
    run_on_error = false
  }

  before_hook "validate_kubectl" {
    commands = ["apply"]
    execute  = ["bash", "-c", "kubectl cluster-info --context ${dependency.base.outputs.cluster_name} 2>/dev/null || (echo 'Warning: kubectl not configured.'; aws eks update-kubeconfig --alias ${dependency.base.outputs.cluster_name} --name ${dependency.base.outputs.cluster_name}; kubectl cluster-info --context ${dependency.base.outputs.cluster_name})"]
  }
}

locals {
  env    = read_terragrunt_config(find_in_parent_folders("env.hcl"))
  common = read_terragrunt_config(find_in_parent_folders("common.hcl"))
}

dependency "base" {
  config_path = "../base"

  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  mock_outputs_merge_strategy_with_state  = "shallow"

  mock_outputs = local.common.locals.mock_outputs_base
}

inputs = {
  remote_state_bucket      = get_env("TF_STATE_BUCKET")
  remote_state_region      = get_env("TF_STATE_REGION", local.env.locals.aws_region)
  remote_state_environment = local.env.locals.environment
  base_state_key           = "base/terraform.tfstate"

  pod_networking_mode = try(local.env.locals.pod_networking_mode, "vpc-cni")
  cilium_networking   = try(local.env.locals.cilium_networking, {})
}

generate "k8s_provider" {
  path      = "k8s_provider_generated.tf"
  if_exists = "overwrite_terragrunt"

  contents = <<-EOF
    # Kubernetes provider configuration
    # Generated by Terragrunt based on base layer outputs

    data "aws_eks_cluster_auth" "cluster" {
      name = "${dependency.base.outputs.cluster_name}"
    }

    provider "kubernetes" {
      host                   = "${dependency.base.outputs.cluster_endpoint}"
      cluster_ca_certificate = base64decode("${dependency.base.outputs.cluster_certificate_authority_data}")
      token                  = data.aws_eks_cluster_auth.cluster.token
    }

    provider "helm" {
      kubernetes {
        host                   = "${dependency.base.outputs.cluster_endpoint}"
        cluster_ca_certificate = base64decode("${dependency.base.outputs.cluster_certificate_authority_data}")
        token                  = data.aws_eks_cluster_auth.cluster.token
      }
    }
  EOF
}
