# Base Infrastructure Layer - EKS Cluster Foundation
#
# This layer creates the foundational EKS cluster infrastructure including:
# - EKS Cluster
# - IAM Roles and Policies (cluster, Fargate, node groups)
# - Security Groups
# - KMS Keys for encryption
# - VPC Endpoints
# - Fargate Profiles
# - EKS Add-ons
# - EC2 Node Groups (optional)
# - Cluster Autoscaler (optional)
#
# This layer has NO dependencies on middleware or application components.

# Note: Backend and provider configurations are generated by Terragrunt
# See: terragrunt.hcl and root terragrunt.hcl

# Data sources
data "aws_region" "current" {}
data "aws_caller_identity" "current" {}

# VPC and Subnets - basic validation that they exist
data "aws_vpc" "selected" {
  id = var.vpc_id
}

data "aws_subnet" "selected" {
  for_each = toset(var.subnet_ids)
  id       = each.value
}

data "aws_route_tables" "private" {
  vpc_id = var.vpc_id

  filter {
    name   = "association.subnet-id"
    values = var.subnet_ids
  }
}

# Local values
locals {
  cluster_name = var.cluster_name
  common_tags = merge(
    {
      Environment = var.environment
      Project     = var.project
      ManagedBy   = "terraform"
      Layer       = "base-infrastructure"
    },
    var.tags
  )

  # Determine if we have any compute resources configured
  has_fargate = length(var.fargate_profiles) > 0
  has_ec2     = length(var.ec2_node_group) > 0

  # Smart public endpoint logic:
  # - If user explicitly sets endpoint_public_access = true AND provides restricted CIDRs, use them
  # - If no restricted CIDRs provided (empty or only 0.0.0.0/0), disable public access
  # - This satisfies CKV_AWS_39 by preventing unrestricted public access
  has_restricted_cidrs   = length(var.public_access_cidrs) > 0 && !contains(var.public_access_cidrs, "0.0.0.0/0")
  enable_public_endpoint = var.endpoint_public_access && local.has_restricted_cidrs
  effective_public_cidrs = local.enable_public_endpoint ? var.public_access_cidrs : []

  node_auto_heal_queue_name      = "${local.cluster_name}-node-auto-heal"
  node_auto_heal_dlq_name        = "${local.cluster_name}-node-auto-heal-dlq"
  node_auto_heal_service_account = "aws-node-termination-handler"
  node_auto_heal_event_patterns = {
    spot_itn = {
      description = "Route EC2 Spot Interruption warnings to SQS"
      pattern = {
        source      = ["aws.ec2"]
        detail-type = ["EC2 Spot Instance Interruption Warning"]
      }
    }
    rebalance = {
      description = "Route EC2 Instance Rebalance recommendations"
      pattern = {
        source      = ["aws.ec2"]
        detail-type = ["EC2 Instance Rebalance Recommendation"]
      }
    }
    state_change = {
      description = "Route EC2 Instance state-change notifications"
      pattern = {
        source      = ["aws.ec2"]
        detail-type = ["EC2 Instance State-change Notification"]
        detail = {
          state = ["stopping", "stopped", "shutting-down", "terminated", "terminating"]
        }
      }
    }
    scheduled_change = {
      description = "Route AWS Health scheduled change notifications for EC2"
      pattern = {
        source      = ["aws.health"]
        detail-type = ["AWS Health Event"]
        detail = {
          service  = ["EC2"]
          category = ["scheduledChange"]
        }
      }
    }
  }
}

# KMS Key for EKS encryption
# KMS Key for cluster-wide encryption
# This single key is shared across:
# - EKS secrets encryption
# - Secrets Manager (ADO PAT)
# - ECR repositories (optional)
# - External Secrets Operator decryption
# This minimizes KMS key sprawl and reduces costs
module "cluster_encryption_key" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/kms_key/aws"
  version = "~> 0.1"

  description             = var.kms_key_description
  deletion_window_in_days = var.kms_key_deletion_window_in_days
  enable_key_rotation     = true
  policy = {
    allow_root_account = {
      sid    = "Enable IAM User Permissions"
      effect = "Allow"
      principals = {
        AWS = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"]
      }
      actions   = ["kms:*"]
      resources = ["*"]
    }
    allow_eks_service = {
      sid    = "Allow use by EKS"
      effect = "Allow"
      principals = {
        Service = ["eks.amazonaws.com"]
      }
      actions = [
        "kms:Encrypt",
        "kms:Decrypt",
        "kms:ReEncrypt*",
        "kms:GenerateDataKey*",
        "kms:DescribeKey"
      ]
      resources = ["*"]
    }
    allow_secrets_manager = {
      sid    = "Allow use by Secrets Manager"
      effect = "Allow"
      principals = {
        Service = ["secretsmanager.amazonaws.com"]
      }
      actions = [
        "kms:Decrypt",
        "kms:GenerateDataKey"
      ]
      resources = ["*"]
      conditions = {
        StringEquals = {
          "kms:ViaService" = ["secretsmanager.${data.aws_region.current.name}.amazonaws.com"]
        }
      }
    }
  }

  tags = merge(local.common_tags, {
    Name = "${local.cluster_name}-cluster-encryption-key"
  })
}

resource "aws_kms_alias" "cluster_encryption" {
  name          = "alias/${local.cluster_name}-cluster-encryption"
  target_key_id = module.cluster_encryption_key.key_id
}

# KMS key is now always created for cluster encryption
locals {
  kms_key_arn = module.cluster_encryption_key.arn
  kms_key_id  = module.cluster_encryption_key.key_id
}

# IAM roles for EKS control plane and Fargate
module "eks_cluster_role" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role/aws"
  version = "~> 0.1"
  count   = var.create_iam_roles ? 1 : 0

  name = "${local.cluster_name}-cluster-role"

  assume_role_policy = [
    {
      actions = ["sts:AssumeRole"]
      principals = [
        {
          type        = "Service"
          identifiers = ["eks.amazonaws.com"]
        }
      ]
    }
  ]

  tags = local.common_tags
}

module "eks_cluster_policy_attachment" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role_policy_attachment/aws"
  version = "~> 0.1"
  count   = var.create_iam_roles ? 1 : 0

  role_name  = module.eks_cluster_role[0].role_name
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
}

module "eks_vpc_resource_controller_attachment" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role_policy_attachment/aws"
  version = "~> 0.1"
  count   = var.create_iam_roles ? 1 : 0

  role_name  = module.eks_cluster_role[0].role_name
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSVPCResourceController"
}

module "fargate_pod_execution_role" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role/aws"
  version = "~> 0.1"
  count   = var.create_iam_roles ? 1 : 0

  name = "${local.cluster_name}-fargate-pod-execution-role"

  assume_role_policy = [
    {
      actions = ["sts:AssumeRole"]
      principals = [
        {
          type        = "Service"
          identifiers = ["eks-fargate-pods.amazonaws.com"]
        }
      ]
    }
  ]

  tags = local.common_tags
}

module "fargate_pod_execution_role_policy_attachment" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role_policy_attachment/aws"
  version = "~> 0.1"
  count   = var.create_iam_roles ? 1 : 0

  role_name  = module.fargate_pod_execution_role[0].role_name
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSFargatePodExecutionRolePolicy"
}

# Security groups
module "cluster_security_group" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/security_group/aws"
  version = "~> 0.1"

  name        = join("-", [local.cluster_name, "cluster"])
  description = "Security group for EKS cluster ${local.cluster_name}"
  vpc_id      = var.vpc_id

  tags = merge(
    local.common_tags,
    {
      Name = "${local.cluster_name}-cluster-sg"
      Type = "EKS-Cluster"
    }
  )
}

module "cluster_security_group_ingress_vpc" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/vpc_security_group_ingress_rule/aws"
  version = "~> 0.1"

  security_group_id = module.cluster_security_group.id
  description       = "Allow HTTPS access from VPC"
  ip_protocol       = "tcp"
  from_port         = 443
  to_port           = 443
  cidr_ipv4         = data.aws_vpc.selected.cidr_block
  tags              = merge(local.common_tags, { Name = "${local.cluster_name}-cluster-sg-api" })
}

module "cluster_security_group_egress_all" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  # checkov:skip=CKV_AWS_382:Unrestricted egress required for EKS control plane to reach AWS APIs and registries.
  source  = "terraform.registry.launch.nttdata.com/module_primitive/vpc_security_group_egress_rule/aws"
  version = "~> 0.1"

  security_group_id = module.cluster_security_group.id
  description       = "Allow all outbound traffic"
  ip_protocol       = "-1"
  cidr_ipv4         = "0.0.0.0/0"
  tags              = merge(local.common_tags, { Name = "${local.cluster_name}-cluster-sg-egress" })
}

module "fargate_security_group" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/security_group/aws"
  version = "~> 0.1"

  name        = join("-", [local.cluster_name, "fargate-pods"])
  description = "Security group for Fargate pods in EKS cluster ${local.cluster_name}"
  vpc_id      = var.vpc_id

  tags = merge(
    local.common_tags,
    {
      Name = "${local.cluster_name}-fargate-pods-sg"
      Type = "EKS-Fargate-Pods"
    }
  )
}

module "fargate_security_group_ingress_from_vpc" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/vpc_security_group_ingress_rule/aws"
  version = "~> 0.1"

  security_group_id = module.fargate_security_group.id
  description       = "Allow all TCP traffic from VPC"
  ip_protocol       = "tcp"
  from_port         = 0
  to_port           = 65535
  cidr_ipv4         = data.aws_vpc.selected.cidr_block
  tags              = merge(local.common_tags, { Name = "${local.cluster_name}-fargate-sg-vpc" })
}

module "fargate_security_group_egress_all" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  # checkov:skip=CKV_AWS_382:Unrestricted egress required for Fargate workloads to reach registries, AWS APIs, and associated services.
  source  = "terraform.registry.launch.nttdata.com/module_primitive/vpc_security_group_egress_rule/aws"
  version = "~> 0.1"

  security_group_id = module.fargate_security_group.id
  description       = "Allow all outbound traffic"
  ip_protocol       = "-1"
  cidr_ipv4         = "0.0.0.0/0"
  tags              = merge(local.common_tags, { Name = "${local.cluster_name}-fargate-sg-egress" })
}

module "fargate_security_group_egress_https" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/vpc_security_group_egress_rule/aws"
  version = "~> 0.1"

  security_group_id = module.fargate_security_group.id
  description       = "Explicit HTTPS outbound for ADO API"
  ip_protocol       = "tcp"
  from_port         = 443
  to_port           = 443
  cidr_ipv4         = "0.0.0.0/0"
  tags              = merge(local.common_tags, { Name = "${local.cluster_name}-fargate-sg-https" })
}

module "fargate_security_group_ingress_from_cluster" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/vpc_security_group_ingress_rule/aws"
  version = "~> 0.1"

  security_group_id            = module.fargate_security_group.id
  referenced_security_group_id = module.cluster_security_group.id
  description                  = "Allow communication from EKS cluster to Fargate pods"
  ip_protocol                  = "tcp"
  from_port                    = 0
  to_port                      = 65535
  tags                         = merge(local.common_tags, { Name = "${local.cluster_name}-cluster-to-fargate" })
}

module "cluster_security_group_ingress_from_fargate" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/vpc_security_group_ingress_rule/aws"
  version = "~> 0.1"

  security_group_id            = module.cluster_security_group.id
  referenced_security_group_id = module.fargate_security_group.id
  description                  = "Allow Fargate pods to communicate with EKS cluster API"
  ip_protocol                  = "tcp"
  from_port                    = 443
  to_port                      = 443
  tags                         = merge(local.common_tags, { Name = "${local.cluster_name}-fargate-to-cluster" })
}

# EKS Cluster
#checkov:skip=CKV_AWS_39:Public endpoint access is restricted to specific CIDRs or disabled based on public_access_cidrs variable
#checkov:skip=CKV_AWS_38:Public endpoint CIDR restrictions enforced via local.enable_public_endpoint logic
module "eks_cluster" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/eks_cluster/aws"
  version = "~> 0.1"

  name                      = local.cluster_name
  role_arn                  = var.create_iam_roles ? module.eks_cluster_role[0].role_arn : var.existing_cluster_role_arn
  kubernetes_version        = var.cluster_version
  enabled_cluster_log_types = var.enabled_cluster_log_types

  vpc_config = {
    subnet_ids = var.subnet_ids
    security_group_ids = compact([
      module.cluster_security_group.id,
      module.fargate_security_group.id
    ])
    endpoint_private_access = true
    endpoint_public_access  = local.enable_public_endpoint
    public_access_cidrs     = local.effective_public_cidrs
  }

  encryption_config = [
    {
      provider_key_arn = local.kms_key_arn
      resources        = ["secrets"]
    }
  ]

  access_config = {
    authentication_mode                         = "API_AND_CONFIG_MAP"
    bootstrap_cluster_creator_admin_permissions = true
  }

  tags = local.common_tags

  depends_on = [
    module.eks_cluster_role,
    module.eks_cluster_policy_attachment,
    module.eks_vpc_resource_controller_attachment
  ]
}

# # Create OIDC provider for IRSA
# resource "aws_iam_openid_connect_provider" "eks" {
#   client_id_list  = ["sts.amazonaws.com"]
#   thumbprint_list = ["9e99a48a9960b14926bb7f3b02e22da2b0ab7280"] # EKS OIDC root CA thumbprint
#   url             = module.eks_cluster.cluster_oidc_issuer_url

#   tags = local.common_tags
# }
# Create OIDC provider for IRSA
module "eks_cluster_oidc" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_openid_connect_provider/aws"
  version = "~> 0.1"

  client_id_list  = ["sts.amazonaws.com"]
  thumbprint_list = ["9e99a48a9960b14926bb7f3b02e22da2b0ab7280"] # EKS OIDC root CA thumbprint
  url             = module.eks_cluster.identity_oidc_issuer

  tags = local.common_tags
}

# IAM Role for VPC CNI using IRSA
module "vpc_cni_irsa_role" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role/aws"
  version = "~> 0.1"
  count   = var.create_iam_roles ? 1 : 0

  name = "${local.cluster_name}-vpc-cni-irsa-role"

  assume_role_policy = [
    {
      actions = ["sts:AssumeRoleWithWebIdentity"]
      principals = [
        {
          type        = "Federated"
          identifiers = [module.eks_cluster_oidc.arn]
        }
      ]
      conditions = [
        {
          test     = "StringEquals"
          variable = "${replace(module.eks_cluster_oidc.url, "https://", "")}:sub"
          values   = ["system:serviceaccount:kube-system:aws-node"]
        },
        {
          test     = "StringEquals"
          variable = "${replace(module.eks_cluster_oidc.url, "https://", "")}:aud"
          values   = ["sts.amazonaws.com"]
        }
      ]
    }
  ]

  tags = local.common_tags
}

# Attach AWS managed policy for VPC CNI
module "vpc_cni_policy_attachment" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role_policy_attachment/aws"
  version = "~> 0.1"
  count   = var.create_iam_roles ? 1 : 0

  role_name  = module.vpc_cni_irsa_role[0].role_name
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
}

# VPC CNI Addon (deployed before compute resources)
resource "aws_eks_addon" "vpc_cni" {
  count = contains(keys(var.eks_addons), "vpc-cni") ? 1 : 0

  cluster_name                = module.eks_cluster.name
  addon_name                  = "vpc-cni"
  addon_version               = try(var.eks_addons["vpc-cni"].addon_version, null)
  service_account_role_arn    = var.create_iam_roles ? module.vpc_cni_irsa_role[0].role_arn : null
  resolve_conflicts_on_create = try(var.eks_addons["vpc-cni"].resolve_conflicts_on_create, "OVERWRITE")
  resolve_conflicts_on_update = try(var.eks_addons["vpc-cni"].resolve_conflicts_on_update, "OVERWRITE")

  depends_on = [
    module.eks_cluster,
    module.eks_cluster_oidc,
    module.vpc_cni_policy_attachment
  ]

  tags = local.common_tags
}

# VPC Endpoints (optional)
module "vpc_endpoints" {
  count  = var.create_vpc_endpoints ? 1 : 0
  source = "./modules/collections/vpc-endpoints"

  cluster_name              = local.cluster_name
  vpc_id                    = var.vpc_id
  subnet_ids                = var.subnet_ids
  route_table_ids           = data.aws_route_tables.private.ids
  security_group_ids        = [module.fargate_security_group.id]
  endpoint_services         = var.vpc_endpoint_services
  exclude_endpoint_services = var.exclude_vpc_endpoint_services

  tags = local.common_tags
}

# Fargate Profiles
# Create one Fargate profile per entry in the fargate_profiles map
# Each profile can have multiple namespace selectors
# IMPORTANT: Fargate pods need VPC CNI addon to be installed first
module "fargate_profile" {
  for_each = var.fargate_profiles
  source   = "./modules/primitive/fargate-profile"

  cluster_name           = module.eks_cluster.name
  profile_name           = "${local.cluster_name}-${each.key}-fargate-profile"
  pod_execution_role_arn = var.create_iam_roles ? module.fargate_pod_execution_role[0].role_arn : var.existing_fargate_role_arn
  subnet_ids             = var.subnet_ids
  selectors              = each.value.selectors

  tags = local.common_tags

  # Wait for IAM roles, cluster, and VPC CNI addon to be ready
  depends_on = [
    module.eks_cluster,
    module.fargate_pod_execution_role,
    aws_eks_addon.vpc_cni
  ]
}

# EKS Addons (excluding VPC CNI which is installed earlier)
# Install remaining addons after compute resources are available
# VPC CNI is handled separately with IRSA before compute resources
resource "aws_eks_addon" "addons" {
  for_each = { for k, v in var.eks_addons : k => v if k != "vpc-cni" }

  cluster_name                = module.eks_cluster.name
  addon_name                  = each.key
  addon_version               = each.value.version
  resolve_conflicts_on_create = try(each.value.resolve_conflicts_on_create, "OVERWRITE")
  resolve_conflicts_on_update = try(each.value.resolve_conflicts_on_update, "OVERWRITE")
  service_account_role_arn    = try(each.value.service_account_role_arn, null)
  configuration_values        = try(each.value.configuration_values, null)

  # Wait for compute resources to be available
  depends_on = [
    module.eks_cluster,
    module.ec2_nodes,
    module.fargate_profile
  ]

  tags = local.common_tags
}

# EC2 Node Groups (optional)
# IMPORTANT: Nodes must wait for VPC CNI addon to be installed before they can join the cluster
module "ec2_nodes" {
  source   = "./modules/primitive/eks-node-group"
  for_each = var.ec2_node_group

  node_group_name = each.key
  cluster_name    = module.eks_cluster.name
  node_role_arn   = module.ec2_node_group_role[0].role_arn
  subnet_ids      = var.subnet_ids
  instance_types  = try(each.value.instance_types, ["t3.medium"])
  disk_size       = try(each.value.disk_size, 50)
  ami_type        = try(each.value.ami_type, null)
  capacity_type   = try(each.value.capacity_type, "ON_DEMAND")
  labels          = try(each.value.labels, {})
  desired_size    = try(each.value.desired_size, 1)
  max_size        = try(each.value.max_size, 3)
  min_size        = try(each.value.min_size, 0)
  taints          = try(each.value.taints, [])

  # Cluster Autoscaler Configuration
  enable_cluster_autoscaler = var.enable_cluster_autoscaler
  cluster_autoscaler_tags = var.enable_cluster_autoscaler ? merge(
    {
      "k8s.io/cluster-autoscaler/node-template/label/eks.amazonaws.com/compute-type" = "ec2"
    },
    # Dynamically create taint labels from the actual taints configuration
    {
      for taint in try(each.value.taints, []) :
      "k8s.io/cluster-autoscaler/node-template/taint/${taint.key}" => "${taint.value}:${taint.effect}"
    },
    # Dynamically create labels from the actual labels configuration
    {
      for label_key, label_value in coalesce(each.value.labels, {}) :
      "k8s.io/cluster-autoscaler/node-template/label/${label_key}" => label_value
    },
    # Optional explicit resource overrides for scale-from-zero accuracy
    {
      for resource_key, resource_value in try(each.value.cluster_autoscaler_node_resources, {}) :
      "k8s.io/cluster-autoscaler/node-template/resources/${resource_key}" => resource_value
    }
  ) : {}

  tags = merge(
    local.common_tags,
    {
      Name = each.key
    },
    try(each.value.tags, {})
  )

  # Wait for VPC CNI addon to be installed before creating nodes
  depends_on = [
    module.eks_cluster,
    aws_eks_addon.vpc_cni,
    module.ec2_node_group_role
  ]
}

# IAM Role for EC2 Node Groups
module "ec2_node_group_role" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role/aws"
  version = "~> 0.1"
  count   = length(var.ec2_node_group) > 0 ? 1 : 0

  name = "${local.cluster_name}-eks-node-group-role"

  assume_role_policy = [
    {
      actions = ["sts:AssumeRole"]
      principals = [
        {
          type        = "Service"
          identifiers = ["ec2.amazonaws.com"]
        }
      ]
    }
  ]

  tags = local.common_tags
}

module "ec2_node_group_policy_attachments" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source   = "terraform.registry.launch.nttdata.com/module_primitive/iam_role_policy_attachment/aws"
  version  = "~> 0.1"
  for_each = length(var.ec2_node_group) > 0 ? toset(var.ec2_node_group_policies) : []

  role_name  = module.ec2_node_group_role[0].role_name
  policy_arn = each.value
}

# Cluster Autoscaler IAM Role (only created if autoscaler is enabled)
module "cluster_autoscaler_role" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role/aws"
  version = "~> 0.1"
  count   = var.enable_cluster_autoscaler ? 1 : 0

  name = "${local.cluster_name}-cluster-autoscaler-role"

  assume_role_policy = [
    {
      actions = ["sts:AssumeRoleWithWebIdentity"]
      principals = [
        {
          type        = "Federated"
          identifiers = [module.eks_cluster_oidc.arn]
        }
      ]
      conditions = [
        {
          test     = "StringEquals"
          variable = "${replace(module.eks_cluster_oidc.url, "https://", "")}:sub"
          values   = ["system:serviceaccount:${var.cluster_autoscaler_namespace}:cluster-autoscaler"]
        },
        {
          test     = "StringEquals"
          variable = "${replace(module.eks_cluster_oidc.url, "https://", "")}:aud"
          values   = ["sts.amazonaws.com"]
        }
      ]
    }
  ]

  tags = local.common_tags
}

module "cluster_autoscaler_policy" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_policy/aws"
  version = "~> 0.1"
  count   = var.enable_cluster_autoscaler ? 1 : 0

  policy_name = "${local.cluster_name}-cluster-autoscaler-policy"

  policy_statement = {
    describe_operations = {
      sid = "DescribeClusterCompute"
      actions = [
        "autoscaling:DescribeAutoScalingGroups",
        "autoscaling:DescribeAutoScalingInstances",
        "autoscaling:DescribeLaunchConfigurations",
        "autoscaling:DescribeScalingActivities",
        "autoscaling:DescribeTags",
        "ec2:DescribeInstanceTypes",
        "ec2:DescribeLaunchTemplateVersions"
      ]
      resources = ["*"]
    }
    manage_asg = {
      sid = "ManageClusterAsg"
      actions = [
        "autoscaling:SetDesiredCapacity",
        "autoscaling:TerminateInstanceInAutoScalingGroup"
      ]
      # Primitive IAM policy module lacks condition support; resource scope keeps parity with prior policy
      resources = [
        "arn:aws:autoscaling:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:autoScalingGroup:*:autoScalingGroupName/*"
      ]
    }
    describe_nodegroup = {
      sid     = "DescribeEksNodegroups"
      actions = ["eks:DescribeNodegroup"]
      resources = [
        "arn:aws:eks:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:nodegroup/${local.cluster_name}/*/*"
      ]
    }
  }

  tags = local.common_tags
}

module "cluster_autoscaler_policy_attachment" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role_policy_attachment/aws"
  version = "~> 0.1"
  count   = var.enable_cluster_autoscaler ? 1 : 0

  role_name  = module.cluster_autoscaler_role[0].role_name
  policy_arn = module.cluster_autoscaler_policy[0].policy_arn
}

# Node Auto-Heal (AWS Node Termination Handler) Infrastructure
resource "aws_sqs_queue" "node_auto_heal_dlq" {
  count = var.enable_node_auto_heal && var.node_auto_heal_enable_dlq ? 1 : 0

  name                       = substr(replace(lower(local.node_auto_heal_dlq_name), "_", "-"), 0, 80)
  message_retention_seconds  = var.node_auto_heal_queue_retention_seconds
  kms_master_key_id          = local.kms_key_arn
  visibility_timeout_seconds = 30
  receive_wait_time_seconds  = 10

  tags = merge(local.common_tags, { Name = local.node_auto_heal_dlq_name })
}

resource "aws_sqs_queue" "node_auto_heal" {
  count = var.enable_node_auto_heal ? 1 : 0

  name                       = substr(replace(lower(local.node_auto_heal_queue_name), "_", "-"), 0, 80)
  message_retention_seconds  = var.node_auto_heal_queue_retention_seconds
  kms_master_key_id          = local.kms_key_arn
  visibility_timeout_seconds = 30
  receive_wait_time_seconds  = 10

  redrive_policy = var.node_auto_heal_enable_dlq ? jsonencode({
    deadLetterTargetArn = aws_sqs_queue.node_auto_heal_dlq[0].arn
    maxReceiveCount     = var.node_auto_heal_dlq_max_receive_count
  }) : null

  tags = merge(local.common_tags, { Name = local.node_auto_heal_queue_name })
}

module "node_auto_heal_event_role" {
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role/aws"
  version = "~> 0.1"
  count   = var.enable_node_auto_heal ? 1 : 0

  name = "${local.cluster_name}-node-auto-heal-events"

  assume_role_policy = [
    {
      actions = ["sts:AssumeRole"]
      principals = [
        {
          type        = "Service"
          identifiers = ["events.amazonaws.com"]
        }
      ]
    }
  ]

  tags = local.common_tags
}

module "node_auto_heal_event_role_policy" {
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_policy/aws"
  version = "~> 0.1"
  count   = var.enable_node_auto_heal ? 1 : 0

  policy_name = "${local.cluster_name}-node-auto-heal-events"

  policy_statement = {
    send_to_queue = {
      sid       = "AllowEventBridgeToSendToQueue"
      actions   = ["sqs:SendMessage"]
      resources = [aws_sqs_queue.node_auto_heal[0].arn]
    }
  }

  tags = local.common_tags
}

module "node_auto_heal_event_role_policy_attachment" {
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role_policy_attachment/aws"
  version = "~> 0.1"
  count   = var.enable_node_auto_heal ? 1 : 0

  role_name  = module.node_auto_heal_event_role[0].role_name
  policy_arn = module.node_auto_heal_event_role_policy[0].policy_arn
}

resource "aws_cloudwatch_event_rule" "node_auto_heal" {
  for_each = { for k, v in local.node_auto_heal_event_patterns : k => v if var.enable_node_auto_heal }

  name          = substr(replace(lower("${local.cluster_name}-${each.key}-node-auto-heal"), "_", "-"), 0, 64)
  description   = each.value.description
  event_pattern = jsonencode(each.value.pattern)
}

resource "aws_cloudwatch_event_target" "node_auto_heal" {
  for_each = { for k, v in local.node_auto_heal_event_patterns : k => v if var.enable_node_auto_heal }

  rule      = aws_cloudwatch_event_rule.node_auto_heal[each.key].name
  target_id = "node-auto-heal-${each.key}"
  arn       = aws_sqs_queue.node_auto_heal[0].arn
  role_arn  = module.node_auto_heal_event_role[0].role_arn
}

module "node_auto_heal_role" {
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role/aws"
  version = "~> 0.1"
  count   = var.enable_node_auto_heal ? 1 : 0

  name = "${local.cluster_name}-node-auto-heal-role"

  assume_role_policy = [
    {
      actions = ["sts:AssumeRoleWithWebIdentity"]
      principals = [
        {
          type        = "Federated"
          identifiers = [module.eks_cluster_oidc.arn]
        }
      ]
      conditions = [
        {
          test     = "StringEquals"
          variable = "${replace(module.eks_cluster_oidc.url, "https://", "")}:sub"
          values   = ["system:serviceaccount:${var.node_auto_heal_namespace}:${local.node_auto_heal_service_account}"]
        },
        {
          test     = "StringEquals"
          variable = "${replace(module.eks_cluster_oidc.url, "https://", "")}:aud"
          values   = ["sts.amazonaws.com"]
        }
      ]
    }
  ]

  tags = local.common_tags
}

module "node_auto_heal_policy" {
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_policy/aws"
  version = "~> 0.1"
  count   = var.enable_node_auto_heal ? 1 : 0

  policy_name = "${local.cluster_name}-node-auto-heal-policy"

  policy_statement = {
    queue_access = {
      sid = "AllowQueueProcessing"
      actions = [
        "sqs:ChangeMessageVisibility",
        "sqs:DeleteMessage",
        "sqs:GetQueueAttributes",
        "sqs:GetQueueUrl",
        "sqs:ReceiveMessage"
      ]
      resources = [aws_sqs_queue.node_auto_heal[0].arn]
    }
    autoscaling = {
      sid = "AllowAutoscalingLifecycle"
      actions = [
        "autoscaling:CompleteLifecycleAction",
        "autoscaling:DescribeAutoScalingGroups",
        "autoscaling:DescribeAutoScalingInstances",
        "autoscaling:DescribeScalingActivities"
      ]
      resources = ["*"]
    }
    ec2_describe = {
      sid = "AllowEc2Describe"
      actions = [
        "ec2:DescribeInstances",
        "ec2:DescribeInstanceStatus",
        "ec2:DescribeTags"
      ]
      resources = ["*"]
    }
  }

  tags = local.common_tags
}

module "node_auto_heal_policy_attachment" {
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role_policy_attachment/aws"
  version = "~> 0.1"
  count   = var.enable_node_auto_heal ? 1 : 0

  role_name  = module.node_auto_heal_role[0].role_name
  policy_arn = module.node_auto_heal_policy[0].policy_arn
}
