# Middleware Layer - Cluster Operators and Services
#
# This layer deploys middleware components that operate on the EKS cluster:
# - KEDA Operator (autoscaling)
# - External Secrets Operator (secret management)
# - Buildkitd service (container builds)
# - Application namespaces
#
# This layer depends on the base infrastructure layer via remote state.

# Note: Backend and provider configurations are generated by Terragrunt
# See: terragrunt.hcl and root terragrunt.hcl
# Kubernetes and Helm providers are configured in k8s_provider_generated.tf

# Data sources
data "aws_region" "current" {}
data "aws_caller_identity" "current" {}

# Base layer state is loaded from remote_state.tf

# Local values
locals {
  cluster_name = data.terraform_remote_state.base.outputs.cluster_name
  common_tags = merge(
    data.terraform_remote_state.base.outputs.common_tags,
    {
      Layer = "middleware"
    },
    var.additional_tags
  )
  cluster_oidc_host          = replace(data.terraform_remote_state.base.outputs.cluster_oidc_issuer_url, "https://", "")
  ado_secret_name            = var.ado_secret_name
  cluster_autoscaler_enabled = try(data.terraform_remote_state.base.outputs.cluster_autoscaler_role_arn, null) != null
  cluster_autoscaler_base_args = [
    "./cluster-autoscaler",
    "--v=4",
    "--stderrthreshold=info",
    "--cloud-provider=aws",
    "--skip-nodes-with-local-storage=false",
    "--expander=least-waste",
    "--node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/${data.terraform_remote_state.base.outputs.cluster_name}",
    "--balance-similar-node-groups",
    "--skip-nodes-with-system-pods=false",
    "--scale-down-enabled=true",
    "--scale-down-delay-after-add=10m",
    "--scale-down-unneeded-time=10m",
    "--scale-down-utilization-threshold=0.5",
    "--max-node-provision-time=15m",
    "--aws-use-static-instance-list=false"
  ]
  cluster_autoscaler_extra_args = flatten([
    for arg_map in [
      try(data.terraform_remote_state.base.outputs.cluster_autoscaler_extra_args, {}),
      var.cluster_autoscaler_additional_args
      ] : [
      for arg_key, arg_val in arg_map : "--${arg_key}=${arg_val}"
    ]
  ])
  node_auto_heal_enabled   = try(data.terraform_remote_state.base.outputs.node_auto_heal_enabled, false)
  node_auto_heal_queue_url = try(data.terraform_remote_state.base.outputs.node_auto_heal_queue_url, null)
  node_auto_heal_role_arn  = try(data.terraform_remote_state.base.outputs.node_auto_heal_role_arn, null)
  node_auto_heal_namespace = try(data.terraform_remote_state.base.outputs.node_auto_heal_namespace, "kube-system")
  node_auto_heal_sa_name   = try(data.terraform_remote_state.base.outputs.node_auto_heal_service_account, "aws-node-termination-handler")

  bk_region              = data.aws_region.current.name
  bk_account             = data.aws_caller_identity.current.account_id
  buildkitd_registry_ids = length(var.buildkitd_ecr_registry_account_ids) > 0 ? var.buildkitd_ecr_registry_account_ids : [local.bk_account]
  buildkitd_ecr_repo_arns = length(var.buildkitd_ecr_repository_arns) > 0 ? var.buildkitd_ecr_repository_arns : [
    "arn:aws:ecr:${local.bk_region}:${local.bk_account}:repository/*"
  ]
  buildkitd_kms_patterns = length(var.buildkitd_kms_key_arn_patterns) > 0 ? var.buildkitd_kms_key_arn_patterns : [
    "arn:aws:kms:${local.bk_region}:${local.bk_account}:key/*"
  ]
  buildkitd_docker_config_json = jsonencode({
    credHelpers = {
      for acc in local.buildkitd_registry_ids :
      "${acc}.dkr.ecr.${local.bk_region}.amazonaws.com" => "ecr-login"
    }
  })
  buildkitd_registry_mirror_config = join("\n", [
    for registry, mirrors in var.buildkitd_registry_mirrors : <<-EOT

      [registry.${jsonencode(registry)}]
        mirrors = ${jsonencode(mirrors)}
    EOT
  ])
  buildkitd_base_args = [
    "--debug",
    "--addr", "tcp://0.0.0.0:1234",
    "--oci-worker-no-process-sandbox",
    "--config", "/etc/buildkit/buildkitd.toml"
  ]
  buildkitd_tls_args = var.buildkitd_tls_enabled ? [
    "--tlscacert", "/etc/buildkit/certs/ca.pem",
    "--tlscert", "/etc/buildkit/certs/cert.pem",
    "--tlskey", "/etc/buildkit/certs/key.pem"
  ] : []

  # kubernetes_manifest uses Kubernetes API field names (camelCase).
  buildkitd_tolerations_for_manifest = [
    for t in var.buildkitd_tolerations : merge(
      {
        key      = t.key
        operator = t.operator
        effect   = t.effect
      },
      try(t.value, null) == null || try(t.value, "") == "" ? {} : { value = t.value }
    )
  ]
}

resource "aws_cloudwatch_log_group" "platform" {
  for_each = var.enable_cloudwatch_observability ? toset(var.platform_log_groups) : []

  name              = "/aws/containerinsights/${local.cluster_name}/${each.value}"
  retention_in_days = var.cloudwatch_log_retention_days
  kms_key_id        = data.terraform_remote_state.base.outputs.kms_key_arn
  tags              = local.common_tags
}

resource "aws_cloudwatch_log_group" "fargate_fluentbit" {
  count = var.enable_cloudwatch_observability && var.enable_fargate_cloudwatch_logging ? 1 : 0

  name              = "/aws/eks/${local.cluster_name}/fargate-fluent-bit"
  retention_in_days = var.cloudwatch_log_retention_days
  kms_key_id        = data.terraform_remote_state.base.outputs.kms_key_arn
  tags              = local.common_tags
}

resource "kubernetes_namespace" "aws_observability" {
  count = var.enable_cloudwatch_observability && var.enable_fargate_cloudwatch_logging ? 1 : 0

  metadata {
    name = "aws-observability"

    labels = {
      "aws-observability" = "enabled"
    }
  }
}

resource "kubernetes_config_map" "fargate_aws_logging" {
  count = var.enable_cloudwatch_observability && var.enable_fargate_cloudwatch_logging ? 1 : 0

  metadata {
    name      = "aws-logging"
    namespace = kubernetes_namespace.aws_observability[0].metadata[0].name
  }

  data = {
    "filters.conf"  = <<-EOT
      [FILTER]
          Name parser
          Match *
          Key_name log
          Parser crio
    EOT
    "output.conf"   = <<-EOT
      [OUTPUT]
          Name cloudwatch
          Match *
          region ${data.aws_region.current.name}
          log_group_name /aws/containerinsights/${local.cluster_name}/application
          log_stream_prefix fargate-
          auto_create_group false
    EOT
    "parsers.conf"  = <<-EOT
      [PARSER]
          Name crio
          Format Regex
          Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
          Time_Key time
          Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    EOT
    "flb_log_cw"    = tostring(var.fargate_fluentbit_include_process_logs)
    "flb_log_level" = var.fargate_fluentbit_log_level
  }

  depends_on = [aws_cloudwatch_log_group.platform]
}

data "aws_iam_policy" "cloudwatch_agent_server" {
  count = var.enable_cloudwatch_observability && var.enable_cloudwatch_observability_addon ? 1 : 0

  arn = "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
}

resource "aws_iam_role_policy_attachment" "cloudwatch_agent_node_role" {
  count = (
    var.enable_cloudwatch_observability &&
    var.enable_cloudwatch_observability_addon &&
    try(data.terraform_remote_state.base.outputs.ec2_node_group_role_name, null) != null
  ) ? 1 : 0

  role       = data.terraform_remote_state.base.outputs.ec2_node_group_role_name
  policy_arn = data.aws_iam_policy.cloudwatch_agent_server[0].arn
}

resource "aws_eks_addon" "cloudwatch_observability" {
  count = var.enable_cloudwatch_observability && var.enable_cloudwatch_observability_addon ? 1 : 0

  cluster_name                = local.cluster_name
  addon_name                  = "amazon-cloudwatch-observability"
  addon_version               = var.cloudwatch_observability_addon_version
  resolve_conflicts_on_create = "OVERWRITE"
  resolve_conflicts_on_update = "OVERWRITE"
  tags                        = local.common_tags

  depends_on = [
    aws_cloudwatch_log_group.platform,
    aws_iam_role_policy_attachment.cloudwatch_agent_node_role
  ]
}

resource "aws_ecr_pull_through_cache_rule" "cache" {
  for_each = var.enable_ecr_pull_through_cache ? var.ecr_pull_through_cache_rules : {}

  ecr_repository_prefix = each.key
  upstream_registry_url = each.value.upstream_registry_url
}

# KEDA Operator IAM Role
module "keda_operator_role" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role/aws"
  version = "~> 0.1"

  name = "${local.cluster_name}-keda-operator-role"

  assume_role_policy = [
    {
      actions = ["sts:AssumeRoleWithWebIdentity"]
      principals = [
        {
          type        = "Federated"
          identifiers = [data.terraform_remote_state.base.outputs.oidc_provider_arn]
        }
      ]
      conditions = [
        {
          test     = "StringEquals"
          variable = "${local.cluster_oidc_host}:sub"
          values   = ["system:serviceaccount:${var.keda_namespace}:keda-operator"]
        },
        {
          test     = "StringEquals"
          variable = "${local.cluster_oidc_host}:aud"
          values   = ["sts.amazonaws.com"]
        }
      ]
    }
  ]

  tags = local.common_tags
}

module "keda_operator_policy" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_policy/aws"
  version = "~> 0.1"

  policy_name = "${local.cluster_name}-keda-operator-policy"

  policy_statement = {
    logs_access = {
      sid = "AllowCloudWatchLogs"
      actions = [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents",
        "logs:DescribeLogStreams"
      ]
      resources = [
        "arn:aws:logs:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:log-group:/aws/eks/${local.cluster_name}/*",
        "arn:aws:logs:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:log-group:keda-operator-*"
      ]
    }
    sqs_queue_access = {
      sid = "AllowSqsQueueAccess"
      actions = [
        "sqs:GetQueueAttributes",
        "sqs:GetQueueUrl"
      ]
      resources = [
        "arn:aws:sqs:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:*"
      ]
    }
    sqs_list_queues = {
      sid     = "AllowSqsListQueues"
      actions = ["sqs:ListQueues"]
      # Primitive policy module lacks condition support; region restriction removed while maintaining resource scope
      resources = ["*"]
    }
    cloudwatch_metrics = {
      sid = "AllowCloudWatchMetrics"
      actions = [
        "cloudwatch:GetMetricStatistics",
        "cloudwatch:ListMetrics"
      ]
      resources = ["*"]
    }
  }

  tags = local.common_tags
}

module "keda_operator_policy_attachment" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role_policy_attachment/aws"
  version = "~> 0.1"

  role_name  = module.keda_operator_role.role_name
  policy_arn = module.keda_operator_policy.policy_arn
}

# External Secrets Operator IAM Role
module "eso_role" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role/aws"
  version = "~> 0.1"

  name = "${local.cluster_name}-external-secrets-role"

  assume_role_policy = [
    {
      actions = ["sts:AssumeRoleWithWebIdentity"]
      principals = [
        {
          type        = "Federated"
          identifiers = [data.terraform_remote_state.base.outputs.oidc_provider_arn]
        }
      ]
      conditions = [
        {
          test     = "StringEquals"
          variable = "${local.cluster_oidc_host}:sub"
          values   = ["system:serviceaccount:${var.eso_namespace}:external-secrets"]
        },
        {
          test     = "StringEquals"
          variable = "${local.cluster_oidc_host}:aud"
          values   = ["sts.amazonaws.com"]
        }
      ]
    }
  ]

  tags = local.common_tags
}

# ESO Policy - Basic Secrets Manager permissions and KMS access
module "eso_policy" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_policy/aws"
  version = "~> 0.1"

  policy_name = "${local.cluster_name}-external-secrets-policy"

  policy_statement = {
    describe_secrets = {
      sid = "AllowSecretsManagerListDescribe"
      actions = [
        "secretsmanager:DescribeSecret",
        "secretsmanager:ListSecrets"
      ]
      resources = [
        "arn:aws:secretsmanager:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:secret:*"
      ]
    }
    kms_access = {
      sid = "AllowKmsForSecrets"
      actions = [
        "kms:Decrypt",
        "kms:DescribeKey"
      ]
      # Primitive policy module lacks condition support; Secrets Manager scoping handled by resource selection
      resources = [data.terraform_remote_state.base.outputs.kms_key_arn]
    }
  }

  tags = local.common_tags
}

module "eso_policy_attachment" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role_policy_attachment/aws"
  version = "~> 0.1"

  role_name  = module.eso_role.role_name
  policy_arn = module.eso_policy.policy_arn
}

# KEDA Operator Installation
module "keda_operator" {
  count  = var.install_keda ? 1 : 0
  source = "./modules/collections/keda-operator"

  cluster_name         = local.cluster_name
  namespace            = var.keda_namespace
  ado_namespace        = var.ado_agents_namespace
  create_namespace     = true
  create_ado_namespace = true
  keda_version         = var.keda_version
  keda_image_tag       = var.keda_version
  webhooks_image_tag   = var.keda_version

  service_account_annotations = {
    "eks.amazonaws.com/role-arn" = module.keda_operator_role.role_arn
  }

  create_ado_secret    = false # ADO secret will be managed by application layer
  eso_managed_secret   = true  # ESO will manage the secret
  ado_secret_name      = local.ado_secret_name
  create_scaled_object = false # ScaledObjects will be created by application layer

  # Configure CloudEventSource controllers via environment variables
  # Disable by default to prevent CrashLoopBackOff in KEDA 2.15.x when CRDs are not installed
  # See: https://github.com/kedacore/keda/issues/5751
  env = [
    {
      name  = "KEDA_ENABLE_CLOUDEVENTSOURCE_CONTROLLER"
      value = tostring(var.keda_enable_cloudeventsource)
    },
    {
      name  = "KEDA_ENABLE_CLUSTERCLOUDEVENTSOURCE_CONTROLLER"
      value = tostring(var.keda_enable_cluster_cloudeventsource)
    }
  ]

  tolerations = [{
    key      = "ks.amazonaws.com/compute-type"
    operator = "Equal"
    value    = "fargate"
    effect   = "NoSchedule"
  }]
}

# Metrics Server (Helm-managed to allow custom arguments)
module "metrics_server" {
  count  = var.install_metrics_server ? 1 : 0
  source = "./modules/collections/metrics-server"

  namespace     = var.metrics_server_namespace
  chart_version = var.metrics_server_chart_version
  args          = var.metrics_server_args
  node_selector = var.metrics_server_node_selector
  tolerations   = var.metrics_server_tolerations
  resources     = var.metrics_server_resources
}

# External Secrets Operator Installation
module "external_secrets_operator" {
  count  = var.install_eso ? 1 : 0
  source = "./modules/collections/external-secrets-operator"

  cluster_name     = local.cluster_name
  namespace        = var.eso_namespace
  create_namespace = true
  eso_version      = var.eso_version
  aws_region       = data.aws_region.current.name

  service_account_annotations = {
    "eks.amazonaws.com/role-arn" = module.eso_role.role_arn
  }

  # Webhook configuration - disabled by default for Fargate compatibility
  webhook_enabled       = var.eso_webhook_enabled
  webhook_failurePolicy = var.eso_webhook_failure_policy

  # ClusterSecretStore is created by deploy.sh config layer (kubectl) due to CRD timing; not Terraform
  create_cluster_secret_store = false

  # Don't create external secrets here - application layer will manage them
  create_external_secrets = false
  external_secrets        = {}

  depends_on = [
    module.keda_operator # Ensure KEDA creates the ADO namespace first
  ]
}

# Cluster Autoscaler Deployment (Kubernetes resources)
module "cluster_autoscaler" {
  count  = local.cluster_autoscaler_enabled ? 1 : 0
  source = "./modules/collections/cluster-autoscaler"

  cluster_name = local.cluster_name
  namespace    = data.terraform_remote_state.base.outputs.cluster_autoscaler_namespace
  aws_region   = data.aws_region.current.name
  image_tag    = data.terraform_remote_state.base.outputs.cluster_autoscaler_version

  service_account_annotations = {
    "eks.amazonaws.com/role-arn" = data.terraform_remote_state.base.outputs.cluster_autoscaler_role_arn
  }

  base_args            = local.cluster_autoscaler_base_args
  extra_args           = local.cluster_autoscaler_extra_args
  node_selector        = var.cluster_autoscaler_node_selector
  tolerations          = var.cluster_autoscaler_tolerations
  resources            = var.cluster_autoscaler_resources
  priority_class_name  = var.cluster_autoscaler_priority_class_name
  replicas             = var.cluster_autoscaler_replicas
  pod_annotations      = var.cluster_autoscaler_pod_annotations
  service_account_name = "cluster-autoscaler"
}

# BuildKit IRSA: registry operations run on the daemon, not the ADO agent pod.
module "buildkit_irsa_role" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  count   = var.enable_buildkitd ? 1 : 0
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role/aws"
  version = "~> 0.1"

  name = "${local.cluster_name}-buildkitd-role"

  assume_role_policy = [
    {
      actions = ["sts:AssumeRoleWithWebIdentity"]
      principals = [
        {
          type        = "Federated"
          identifiers = [data.terraform_remote_state.base.outputs.oidc_provider_arn]
        }
      ]
      conditions = [
        {
          test     = "StringEquals"
          variable = "${local.cluster_oidc_host}:sub"
          values   = ["system:serviceaccount:${var.buildkitd_namespace}:buildkitd"]
        },
        {
          test     = "StringEquals"
          variable = "${local.cluster_oidc_host}:aud"
          values   = ["sts.amazonaws.com"]
        }
      ]
    }
  ]

  tags = merge(local.common_tags, {
    Role      = "buildkitd"
    Component = "buildkitd"
  })
}

module "buildkit_irsa_policy" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  count   = var.enable_buildkitd ? 1 : 0
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_policy/aws"
  version = "~> 0.1"

  policy_name = "${local.cluster_name}-buildkitd-ecr-policy"

  policy_statement = {
    ecr_get_auth = {
      sid       = "ECRGetAuth"
      actions   = ["ecr:GetAuthorizationToken"]
      resources = ["*"]
    }
    ecr_push_pull = {
      sid = "ECRPushPull"
      actions = [
        "ecr:BatchCheckLayerAvailability",
        "ecr:GetDownloadUrlForLayer",
        "ecr:BatchGetImage",
        "ecr:InitiateLayerUpload",
        "ecr:UploadLayerPart",
        "ecr:CompleteLayerUpload",
        "ecr:PutImage"
      ]
      resources = local.buildkitd_ecr_repo_arns
    }
    kms_for_ecr = {
      sid = "KMSForECR"
      actions = [
        "kms:Decrypt",
        "kms:DescribeKey",
        "kms:GenerateDataKey"
      ]
      resources = local.buildkitd_kms_patterns
    }
  }

  tags = merge(local.common_tags, {
    Role      = "buildkitd"
    Component = "buildkitd"
  })
}

module "buildkit_irsa_policy_attachment" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  count   = var.enable_buildkitd ? 1 : 0
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role_policy_attachment/aws"
  version = "~> 0.1"

  role_name  = module.buildkit_irsa_role[0].role_name
  policy_arn = module.buildkit_irsa_policy[0].policy_arn
}

# Buildkitd Service (standalone deployment for cluster-wide availability)
resource "kubernetes_namespace" "buildkit" {
  count = var.enable_buildkitd ? 1 : 0

  metadata {
    name = var.buildkitd_namespace

    labels = {
      "pod-security.kubernetes.io/enforce" = "privileged"
      "pod-security.kubernetes.io/audit"   = "privileged"
      "pod-security.kubernetes.io/warn"    = "privileged"
    }
  }
}

resource "kubernetes_service_account" "buildkitd" {
  count = var.enable_buildkitd ? 1 : 0

  metadata {
    name      = "buildkitd"
    namespace = kubernetes_namespace.buildkit[0].metadata[0].name
    annotations = {
      "eks.amazonaws.com/role-arn" = module.buildkit_irsa_role[0].role_arn
    }
  }
}

resource "kubernetes_config_map" "buildkitd_docker_config" {
  count = var.enable_buildkitd ? 1 : 0

  metadata {
    name      = "buildkitd-docker-config"
    namespace = kubernetes_namespace.buildkit[0].metadata[0].name
  }

  data = {
    "config.json" = local.buildkitd_docker_config_json
  }
}

resource "kubernetes_config_map" "buildkitd_config" {
  count = var.enable_buildkitd ? 1 : 0

  metadata {
    name      = "buildkitd-config"
    namespace = kubernetes_namespace.buildkit[0].metadata[0].name
  }

  data = {
    "buildkitd.toml" = <<-EOT
      [worker.oci]
        max-parallelism = 1
      ${local.buildkitd_registry_mirror_config}
    EOT
  }
}

# Rootless BuildKit: use kubernetes_manifest so we can set securityContext.appArmorProfile (K8s 1.30+).
# The kubernetes_deployment resource schema does not expose appArmorProfile; the old Pod annotation is deprecated.
# checkov:skip=CKV_K8S_43:Image tag passed via variable for maintainability.
# checkov:skip=CKV_K8S_14:Image tag passed via variable.
resource "kubernetes_manifest" "buildkitd" {
  count = var.enable_buildkitd ? 1 : 0

  manifest = {
    apiVersion = "apps/v1"
    kind       = "Deployment"
    metadata = {
      name      = "buildkitd"
      namespace = kubernetes_namespace.buildkit[0].metadata[0].name
      labels = {
        app = "buildkitd"
      }
    }
    spec = {
      replicas = var.buildkitd_replicas
      selector = {
        matchLabels = {
          app = "buildkitd"
        }
      }
      template = {
        metadata = {
          labels = {
            app = "buildkitd"
          }
        }
        spec = {
          serviceAccountName = kubernetes_service_account.buildkitd[0].metadata[0].name
          nodeSelector       = var.buildkitd_node_selector
          tolerations        = local.buildkitd_tolerations_for_manifest
          topologySpreadConstraints = var.buildkitd_topology_spread_enabled ? [
            {
              maxSkew           = 1
              topologyKey       = "topology.kubernetes.io/zone"
              whenUnsatisfiable = "ScheduleAnyway"
              labelSelector = {
                matchLabels = {
                  app = "buildkitd"
                }
              }
            }
          ] : []
          initContainers = [
            {
              name    = "install-ecr-credential-helper"
              image   = "public.ecr.aws/docker/library/alpine:3.20"
              command = ["/bin/sh", "-c"]
              args = [
                "set -eu; apk add --no-cache curl ca-certificates; curl -sSL -o /helper/docker-credential-ecr-login \"https://github.com/awslabs/amazon-ecr-credential-helper/releases/download/v0.12.0/docker-credential-ecr-login-linux-amd64\"; chmod +x /helper/docker-credential-ecr-login"
              ]
              volumeMounts = [
                {
                  name      = "ecr-helper-bin"
                  mountPath = "/helper"
                }
              ]
              resources = {
                requests = {
                  cpu    = "100m"
                  memory = "64Mi"
                }
                limits = {
                  cpu    = "500m"
                  memory = "128Mi"
                }
              }
            }
          ]
          containers = [
            {
              name            = "buildkitd"
              image           = var.buildkitd_image
              imagePullPolicy = "Always"
              ports = [
                {
                  name          = "buildkitd"
                  containerPort = 1234
                  protocol      = "TCP"
                }
              ]
              env = [
                { name = "AWS_DEFAULT_REGION", value = data.aws_region.current.name },
                { name = "AWS_EC2_METADATA_DISABLED", value = "true" },
                { name = "DOCKER_CONFIG", value = "/home/user/.docker" },
                { name = "PATH", value = "/ecr:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" }
              ]
              args = concat(local.buildkitd_base_args, local.buildkitd_tls_args)
              securityContext = {
                runAsUser                = 1000
                runAsGroup               = 1000
                runAsNonRoot             = true
                readOnlyRootFilesystem   = false
                allowPrivilegeEscalation = true
                seccompProfile = {
                  type = "Unconfined"
                }
                appArmorProfile = {
                  type = "Unconfined"
                }
              }
              readinessProbe = {
                tcpSocket = {
                  port = 1234
                }
                initialDelaySeconds = 5
                periodSeconds       = 10
              }
              livenessProbe = {
                tcpSocket = {
                  port = 1234
                }
                initialDelaySeconds = 10
                periodSeconds       = 20
              }
              resources = {
                requests = {
                  cpu    = var.buildkitd_resources.requests.cpu
                  memory = var.buildkitd_resources.requests.memory
                }
                limits = {
                  cpu    = var.buildkitd_resources.limits.cpu
                  memory = var.buildkitd_resources.limits.memory
                }
              }
              volumeMounts = concat([
                { name = "tmp", mountPath = "/tmp" },
                { name = "buildkit-rootless", mountPath = "/home/user/.local/share/buildkit" },
                { name = "run", mountPath = "/run" },
                { name = "buildkitd-config", mountPath = "/etc/buildkit" },
                { name = "ecr-helper-bin", mountPath = "/ecr", readOnly = true },
                { name = "buildkit-docker-config", mountPath = "/home/user/.docker", readOnly = true }
                ], var.buildkitd_tls_enabled ? [
                { name = "buildkit-tls", mountPath = "/etc/buildkit/certs", readOnly = true }
              ] : [])
            }
          ]
          volumes = concat([
            { name = "ecr-helper-bin", emptyDir = {} },
            {
              name = "buildkit-docker-config"
              configMap = {
                name = kubernetes_config_map.buildkitd_docker_config[0].metadata[0].name
                items = [
                  {
                    key  = "config.json"
                    path = "config.json"
                  }
                ]
              }
            },
            {
              name = "buildkitd-config"
              configMap = {
                name = kubernetes_config_map.buildkitd_config[0].metadata[0].name
              }
            },
            { name = "tmp", emptyDir = {} },
            { name = "run", emptyDir = {} },
            {
              name = "buildkit-rootless"
              emptyDir = {
                sizeLimit = var.buildkitd_storage_size
              }
            }
            ], var.buildkitd_tls_enabled ? [
            {
              name = "buildkit-tls"
              secret = {
                secretName = var.buildkitd_tls_secret_name
              }
            }
          ] : [])
        }
      }
    }
  }

  computed_fields = [
    "metadata.generation",
    "metadata.resourceVersion",
    "metadata.uid",
    "status",
  ]
}

resource "kubernetes_pod_disruption_budget_v1" "buildkitd" {
  count = var.enable_buildkitd && var.buildkitd_pdb_enabled ? 1 : 0

  metadata {
    name      = "buildkitd"
    namespace = kubernetes_namespace.buildkit[0].metadata[0].name
    labels = {
      app = "buildkitd"
    }
  }

  spec {
    min_available = var.buildkitd_pdb_min_available

    selector {
      match_labels = {
        app = "buildkitd"
      }
    }
  }
}

resource "kubernetes_service" "buildkitd" {
  count = var.enable_buildkitd ? 1 : 0

  metadata {
    name      = "buildkitd"
    namespace = kubernetes_namespace.buildkit[0].metadata[0].name

    labels = {
      app = "buildkitd"
    }
  }

  spec {
    selector = {
      app = "buildkitd"
    }

    port {
      port        = 1234
      target_port = 1234
      protocol    = "TCP"
      name        = "buildkitd"
    }

    type = "ClusterIP"
  }
}

# Create an ExternalName service alias in the ado-agents namespace
# This allows ADO agents to reference buildkitd as:
# - buildkitd.ado-agents.svc.cluster.local
# - buildkitd (from within the ado-agents namespace)
# Instead of the full: buildkitd.buildkit-system.svc.cluster.local
resource "kubernetes_service" "buildkitd_alias" {
  count = var.enable_buildkitd ? 1 : 0

  metadata {
    name      = "buildkit"
    namespace = var.ado_agents_namespace

    labels = {
      app = "buildkitd"
    }

    annotations = {
      "description" = "ExternalName service alias to buildkitd in buildkit-system namespace"
    }
  }

  spec {
    type          = "ExternalName"
    external_name = "buildkitd.${var.buildkitd_namespace}.svc.cluster.local"
  }

  depends_on = [
    kubernetes_service.buildkitd,
    module.keda_operator # Ensures ado-agents namespace exists
  ]
}

resource "kubernetes_horizontal_pod_autoscaler_v2" "buildkitd" {
  count = var.enable_buildkitd && var.buildkitd_hpa_enabled ? 1 : 0

  metadata {
    name      = "buildkitd"
    namespace = var.buildkitd_namespace
    labels = {
      app = "buildkitd"
    }
  }

  spec {
    min_replicas = var.buildkitd_hpa_min_replicas
    max_replicas = var.buildkitd_hpa_max_replicas

    scale_target_ref {
      api_version = "apps/v1"
      kind        = "Deployment"
      name        = "buildkitd"
    }

    metric {
      type = "Resource"
      resource {
        name = "memory"
        target {
          type                = "Utilization"
          average_utilization = var.buildkitd_hpa_target_memory_utilization_percentage
        }
      }
    }
  }

  depends_on = [kubernetes_manifest.buildkitd]
}

# AWS Node Termination Handler (queue processor mode)
module "node_termination_handler" {
  count  = local.node_auto_heal_enabled && local.node_auto_heal_queue_url != null && local.node_auto_heal_role_arn != null ? 1 : 0
  source = "./modules/collections/node-termination-handler"

  namespace            = local.node_auto_heal_namespace
  create_namespace     = false
  queue_url            = local.node_auto_heal_queue_url
  aws_region           = data.aws_region.current.name
  chart_version        = var.node_auto_heal_chart_version
  log_level            = var.node_auto_heal_log_level
  service_account_name = local.node_auto_heal_sa_name
  service_account_annotations = {
    "eks.amazonaws.com/role-arn" = local.node_auto_heal_role_arn
  }
  node_selector = var.node_auto_heal_daemonset_node_selector
  tolerations   = var.node_auto_heal_daemonset_tolerations
  resources     = var.node_auto_heal_daemonset_resources
}
