# Middleware Layer - Cluster Operators and Services
#
# This layer deploys middleware components that operate on the EKS cluster:
# - KEDA Operator (autoscaling)
# - External Secrets Operator (secret management)
# - Buildkitd service (container builds)
# - Application namespaces
#
# This layer depends on the base infrastructure layer via remote state.

# Note: Backend and provider configurations are generated by Terragrunt
# See: terragrunt.hcl and root terragrunt.hcl
# Kubernetes and Helm providers are configured in k8s_provider_generated.tf

# Data sources
data "aws_region" "current" {}
data "aws_caller_identity" "current" {}

# Base layer state is loaded from remote_state.tf

# Local values
locals {
  cluster_name = data.terraform_remote_state.base.outputs.cluster_name
  common_tags = merge(
    data.terraform_remote_state.base.outputs.common_tags,
    {
      Layer = "middleware"
    },
    var.additional_tags
  )
  cluster_oidc_host          = replace(data.terraform_remote_state.base.outputs.cluster_oidc_issuer_url, "https://", "")
  ado_secret_name            = var.ado_secret_name
  cluster_autoscaler_enabled = try(data.terraform_remote_state.base.outputs.cluster_autoscaler_role_arn, null) != null
  cluster_autoscaler_base_args = [
    "./cluster-autoscaler",
    "--v=4",
    "--stderrthreshold=info",
    "--cloud-provider=aws",
    "--skip-nodes-with-local-storage=false",
    "--expander=least-waste",
    "--node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/${data.terraform_remote_state.base.outputs.cluster_name}",
    "--balance-similar-node-groups",
    "--skip-nodes-with-system-pods=false",
    "--scale-down-enabled=true",
    "--scale-down-delay-after-add=10m",
    "--scale-down-unneeded-time=10m",
    "--scale-down-utilization-threshold=0.5",
    "--max-node-provision-time=15m",
    "--aws-use-static-instance-list=false"
  ]
  cluster_autoscaler_extra_args = flatten([
    for arg_map in [
      try(data.terraform_remote_state.base.outputs.cluster_autoscaler_extra_args, {}),
      var.cluster_autoscaler_additional_args
      ] : [
      for arg_key, arg_val in arg_map : "--${arg_key}=${arg_val}"
    ]
  ])
  node_auto_heal_enabled   = try(data.terraform_remote_state.base.outputs.node_auto_heal_enabled, false)
  node_auto_heal_queue_url = try(data.terraform_remote_state.base.outputs.node_auto_heal_queue_url, null)
  node_auto_heal_role_arn  = try(data.terraform_remote_state.base.outputs.node_auto_heal_role_arn, null)
  node_auto_heal_namespace = try(data.terraform_remote_state.base.outputs.node_auto_heal_namespace, "kube-system")
  node_auto_heal_sa_name   = try(data.terraform_remote_state.base.outputs.node_auto_heal_service_account, "aws-node-termination-handler")
}

# KEDA Operator IAM Role
module "keda_operator_role" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role/aws"
  version = "~> 0.1"

  name = "${local.cluster_name}-keda-operator-role"

  assume_role_policy = [
    {
      actions = ["sts:AssumeRoleWithWebIdentity"]
      principals = [
        {
          type        = "Federated"
          identifiers = [data.terraform_remote_state.base.outputs.oidc_provider_arn]
        }
      ]
      conditions = [
        {
          test     = "StringEquals"
          variable = "${local.cluster_oidc_host}:sub"
          values   = ["system:serviceaccount:${var.keda_namespace}:keda-operator"]
        },
        {
          test     = "StringEquals"
          variable = "${local.cluster_oidc_host}:aud"
          values   = ["sts.amazonaws.com"]
        }
      ]
    }
  ]

  tags = local.common_tags
}

module "keda_operator_policy" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_policy/aws"
  version = "~> 0.1"

  policy_name = "${local.cluster_name}-keda-operator-policy"

  policy_statement = {
    logs_access = {
      sid = "AllowCloudWatchLogs"
      actions = [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents",
        "logs:DescribeLogStreams"
      ]
      resources = [
        "arn:aws:logs:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:log-group:/aws/eks/${local.cluster_name}/*",
        "arn:aws:logs:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:log-group:keda-operator-*"
      ]
    }
    sqs_queue_access = {
      sid = "AllowSqsQueueAccess"
      actions = [
        "sqs:GetQueueAttributes",
        "sqs:GetQueueUrl"
      ]
      resources = [
        "arn:aws:sqs:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:*"
      ]
    }
    sqs_list_queues = {
      sid     = "AllowSqsListQueues"
      actions = ["sqs:ListQueues"]
      # Primitive policy module lacks condition support; region restriction removed while maintaining resource scope
      resources = ["*"]
    }
    cloudwatch_metrics = {
      sid = "AllowCloudWatchMetrics"
      actions = [
        "cloudwatch:GetMetricStatistics",
        "cloudwatch:ListMetrics"
      ]
      resources = ["*"]
    }
  }

  tags = local.common_tags
}

module "keda_operator_policy_attachment" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role_policy_attachment/aws"
  version = "~> 0.1"

  role_name  = module.keda_operator_role.role_name
  policy_arn = module.keda_operator_policy.policy_arn
}

# External Secrets Operator IAM Role
module "eso_role" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role/aws"
  version = "~> 0.1"

  name = "${local.cluster_name}-external-secrets-role"

  assume_role_policy = [
    {
      actions = ["sts:AssumeRoleWithWebIdentity"]
      principals = [
        {
          type        = "Federated"
          identifiers = [data.terraform_remote_state.base.outputs.oidc_provider_arn]
        }
      ]
      conditions = [
        {
          test     = "StringEquals"
          variable = "${local.cluster_oidc_host}:sub"
          values   = ["system:serviceaccount:${var.eso_namespace}:external-secrets"]
        },
        {
          test     = "StringEquals"
          variable = "${local.cluster_oidc_host}:aud"
          values   = ["sts.amazonaws.com"]
        }
      ]
    }
  ]

  tags = local.common_tags
}

# ESO Policy - Basic Secrets Manager permissions and KMS access
module "eso_policy" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_policy/aws"
  version = "~> 0.1"

  policy_name = "${local.cluster_name}-external-secrets-policy"

  policy_statement = {
    describe_secrets = {
      sid = "AllowSecretsManagerListDescribe"
      actions = [
        "secretsmanager:DescribeSecret",
        "secretsmanager:ListSecrets"
      ]
      resources = [
        "arn:aws:secretsmanager:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:secret:*"
      ]
    }
    kms_access = {
      sid = "AllowKmsForSecrets"
      actions = [
        "kms:Decrypt",
        "kms:DescribeKey"
      ]
      # Primitive policy module lacks condition support; Secrets Manager scoping handled by resource selection
      resources = [data.terraform_remote_state.base.outputs.kms_key_arn]
    }
  }

  tags = local.common_tags
}

module "eso_policy_attachment" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role_policy_attachment/aws"
  version = "~> 0.1"

  role_name  = module.eso_role.role_name
  policy_arn = module.eso_policy.policy_arn
}

# KEDA Operator Installation
module "keda_operator" {
  count  = var.install_keda ? 1 : 0
  source = "./modules/primitive/keda-operator"

  cluster_name         = local.cluster_name
  namespace            = var.keda_namespace
  ado_namespace        = var.ado_agents_namespace
  create_namespace     = true
  create_ado_namespace = true
  keda_version         = var.keda_version

  service_account_annotations = {
    "eks.amazonaws.com/role-arn" = module.keda_operator_role.role_arn
  }

  create_ado_secret    = false # ADO secret will be managed by application layer
  eso_managed_secret   = true  # ESO will manage the secret
  ado_secret_name      = local.ado_secret_name
  create_scaled_object = false # ScaledObjects will be created by application layer

  # Configure CloudEventSource controllers via environment variables
  # Disable by default to prevent CrashLoopBackOff in KEDA 2.15.x when CRDs are not installed
  # See: https://github.com/kedacore/keda/issues/5751
  env = [
    {
      name  = "KEDA_ENABLE_CLOUDEVENTSOURCE_CONTROLLER"
      value = tostring(var.keda_enable_cloudeventsource)
    },
    {
      name  = "KEDA_ENABLE_CLUSTERCLOUDEVENTSOURCE_CONTROLLER"
      value = tostring(var.keda_enable_cluster_cloudeventsource)
    }
  ]

  tolerations = [{
    key      = "ks.amazonaws.com/compute-type"
    operator = "Equal"
    value    = "fargate"
    effect   = "NoSchedule"
  }]
}

# Metrics Server (Helm-managed to allow custom arguments)
module "metrics_server" {
  count  = var.install_metrics_server ? 1 : 0
  source = "./modules/primitive/metrics-server"

  namespace     = var.metrics_server_namespace
  chart_version = var.metrics_server_chart_version
  args          = var.metrics_server_args
  node_selector = var.metrics_server_node_selector
  tolerations   = var.metrics_server_tolerations
  resources     = var.metrics_server_resources
}

# External Secrets Operator Installation
module "external_secrets_operator" {
  count  = var.install_eso ? 1 : 0
  source = "./modules/primitive/external-secrets-operator"

  cluster_name     = local.cluster_name
  namespace        = var.eso_namespace
  create_namespace = true
  eso_version      = var.eso_version
  aws_region       = data.aws_region.current.name

  service_account_annotations = {
    "eks.amazonaws.com/role-arn" = module.eso_role.role_arn
  }

  # Webhook configuration - disabled by default for Fargate compatibility
  webhook_enabled       = var.eso_webhook_enabled
  webhook_failurePolicy = var.eso_webhook_failure_policy

  # ClusterSecretStore is NOT created by Terraform (CRD timing limitation)
  # Must be created post-deployment using post-deploy-middleware.sh script
  # See: docs/MIDDLEWARE_POST_DEPLOYMENT_STEPS.md
  create_cluster_secret_store = false

  # Don't create external secrets here - application layer will manage them
  create_external_secrets = false
  external_secrets        = {}

  depends_on = [
    module.keda_operator # Ensure KEDA creates the ADO namespace first
  ]
}

# Cluster Autoscaler Deployment (Kubernetes resources)
module "cluster_autoscaler" {
  count  = local.cluster_autoscaler_enabled ? 1 : 0
  source = "./modules/primitive/cluster-autoscaler"

  cluster_name = local.cluster_name
  namespace    = data.terraform_remote_state.base.outputs.cluster_autoscaler_namespace
  aws_region   = data.aws_region.current.name
  image_tag    = data.terraform_remote_state.base.outputs.cluster_autoscaler_version

  service_account_annotations = {
    "eks.amazonaws.com/role-arn" = data.terraform_remote_state.base.outputs.cluster_autoscaler_role_arn
  }

  base_args            = local.cluster_autoscaler_base_args
  extra_args           = local.cluster_autoscaler_extra_args
  node_selector        = var.cluster_autoscaler_node_selector
  tolerations          = var.cluster_autoscaler_tolerations
  resources            = var.cluster_autoscaler_resources
  priority_class_name  = var.cluster_autoscaler_priority_class_name
  replicas             = var.cluster_autoscaler_replicas
  pod_annotations      = var.cluster_autoscaler_pod_annotations
  service_account_name = "cluster-autoscaler"
}

# Buildkitd Service (standalone deployment for cluster-wide availability)
resource "kubernetes_namespace" "buildkit" {
  count = var.enable_buildkitd ? 1 : 0

  metadata {
    name = var.buildkitd_namespace

    labels = {
      "pod-security.kubernetes.io/enforce" = "privileged"
      "pod-security.kubernetes.io/audit"   = "privileged"
      "pod-security.kubernetes.io/warn"    = "privileged"
    }
  }
}

resource "kubernetes_deployment" "buildkitd" {
  # Rootless BuildKit deployment aligned with https://github.com/moby/buildkit/tree/master/examples/kubernetes
  # checkov:skip=CKV_K8S_43:Using tag-based image references for maintainability. Digest-based references make updates difficult and provide minimal security benefit in this controlled environment
  # checkov:skip=CKV_K8S_14:Image tag is passed as variable. 
  count = var.enable_buildkitd ? 1 : 0

  metadata {
    name      = "buildkitd"
    namespace = kubernetes_namespace.buildkit[0].metadata[0].name

    labels = {
      app = "buildkitd"
    }
  }

  spec {
    replicas = var.buildkitd_replicas

    selector {
      match_labels = {
        app = "buildkitd"
      }
    }

      template {
        metadata {
          labels = {
            app = "buildkitd"
          }

            annotations = {
              "container.apparmor.security.beta.kubernetes.io/buildkitd" = "unconfined"
            }
        }

      spec {
        # Use node selector for EC2 nodes if available
        node_selector = var.buildkitd_node_selector

        # Tolerations for dedicated buildkit nodes
        dynamic "toleration" {
          for_each = var.buildkitd_tolerations
          content {
            key      = toleration.value.key
            operator = toleration.value.operator
            value    = toleration.value.value
            effect   = toleration.value.effect
          }
        }

        container {
          name              = "buildkitd"
          image             = var.buildkitd_image
          image_pull_policy = "Always"

          port {
            container_port = 1234
            name           = "buildkitd"
            protocol       = "TCP"
          }

          # Enable debug logging and expose the TCP listener without TLS. Rootless mode
          # requires the no-process-sandbox flag to avoid privileged operations.
          args = [
            "--debug",
            "--addr", "tcp://0.0.0.0:1234",
            "--oci-worker-no-process-sandbox"
          ]

          # Rootless deployment runs as an unprivileged user with explicit seccomp/AppArmor
          # settings, matching the upstream example.
          security_context {
            run_as_user               = 1000
            run_as_group              = 1000
            run_as_non_root           = true
            read_only_root_filesystem = false
            # Allow setuid helpers like newuidmap/newgidmap to initialize user namespaces
            allow_privilege_escalation = true

            seccomp_profile {
              type = "Unconfined"
            }
          }

          # Readiness probe to ensure buildkitd is ready before routing traffic
          readiness_probe {
            tcp_socket {
              port = 1234
            }
            initial_delay_seconds = 5
            period_seconds        = 10
          }

          # Liveness probe to restart unhealthy buildkitd pods
          liveness_probe {
            tcp_socket {
              port = 1234
            }
            initial_delay_seconds = 10
            period_seconds        = 20
          }

          resources {
            requests = {
              cpu    = var.buildkitd_resources.requests.cpu
              memory = var.buildkitd_resources.requests.memory
            }
            limits = {
              cpu    = var.buildkitd_resources.limits.cpu
              memory = var.buildkitd_resources.limits.memory
            }
          }

          volume_mount {
            mount_path = "/tmp"
            name       = "tmp"
          }

          volume_mount {
            mount_path = "/home/user/.local/share/buildkit"
            name       = "buildkit-rootless"
          }

          volume_mount {
            mount_path = "/run"
            name       = "run"
          }
        }

        volume {
          name = "tmp"
          empty_dir {}
        }

        volume {
          name = "run"
          empty_dir {}
        }

        volume {
          name = "buildkit-rootless"
          empty_dir {
            size_limit = var.buildkitd_storage_size
          }
        }
      }
    }
  }
}

resource "kubernetes_service" "buildkitd" {
  count = var.enable_buildkitd ? 1 : 0

  metadata {
    name      = "buildkitd"
    namespace = kubernetes_namespace.buildkit[0].metadata[0].name

    labels = {
      app = "buildkitd"
    }
  }

  spec {
    selector = {
      app = "buildkitd"
    }

    port {
      port        = 1234
      target_port = 1234
      protocol    = "TCP"
      name        = "buildkitd"
    }

    type = "ClusterIP"
  }
}

# Create an ExternalName service alias in the ado-agents namespace
# This allows ADO agents to reference buildkitd as:
# - buildkitd.ado-agents.svc.cluster.local
# - buildkitd (from within the ado-agents namespace)
# Instead of the full: buildkitd.buildkit-system.svc.cluster.local
resource "kubernetes_service" "buildkitd_alias" {
  count = var.enable_buildkitd ? 1 : 0

  metadata {
    name      = "buildkit"
    namespace = var.ado_agents_namespace

    labels = {
      app = "buildkitd"
    }

    annotations = {
      "description" = "ExternalName service alias to buildkitd in buildkit-system namespace"
    }
  }

  spec {
    type          = "ExternalName"
    external_name = "buildkitd.${var.buildkitd_namespace}.svc.cluster.local"
  }

  depends_on = [
    kubernetes_service.buildkitd,
    module.keda_operator # Ensures ado-agents namespace exists
  ]
}

resource "kubernetes_horizontal_pod_autoscaler_v2" "buildkitd" {
  count = var.enable_buildkitd && var.buildkitd_hpa_enabled ? 1 : 0

  metadata {
    name      = "buildkitd"
    namespace = var.buildkitd_namespace
    labels = {
      app = "buildkitd"
    }
  }

  spec {
    min_replicas = var.buildkitd_hpa_min_replicas
    max_replicas = var.buildkitd_hpa_max_replicas

    scale_target_ref {
      api_version = "apps/v1"
      kind        = "Deployment"
      name        = "buildkitd"
    }

    metric {
      type = "Resource"
      resource {
        name = "memory"
        target {
          type                = "Utilization"
          average_utilization = var.buildkitd_hpa_target_memory_utilization_percentage
        }
      }
    }
  }

  depends_on = [kubernetes_deployment.buildkitd]
}

# AWS Node Termination Handler (queue processor mode)
module "node_termination_handler" {
  count  = local.node_auto_heal_enabled && local.node_auto_heal_queue_url != null && local.node_auto_heal_role_arn != null ? 1 : 0
  source = "./modules/primitive/node-termination-handler"

  namespace            = local.node_auto_heal_namespace
  create_namespace     = false
  queue_url            = local.node_auto_heal_queue_url
  aws_region           = data.aws_region.current.name
  chart_version        = var.node_auto_heal_chart_version
  log_level            = var.node_auto_heal_log_level
  service_account_name = local.node_auto_heal_sa_name
  service_account_annotations = {
    "eks.amazonaws.com/role-arn" = local.node_auto_heal_role_arn
  }
  node_selector = var.node_auto_heal_daemonset_node_selector
  tolerations   = var.node_auto_heal_daemonset_tolerations
  resources     = var.node_auto_heal_daemonset_resources
}