# Application Layer - ADO Agents and Application Resources
#
# This layer deploys application-specific resources:
# - ECR repositories for agent container images
# - AWS Secrets Manager secrets for ADO integration
# - Helm chart deployment for ADO agents
# - IAM roles for agent execution (IRSA)
#
# This layer depends on both base infrastructure and middleware layers.

# Note: Backend and provider configurations are generated by Terragrunt
# See: terragrunt.hcl and root terragrunt.hcl
# Kubernetes and Helm providers are configured in k8s_provider_generated.tf

# Data sources
data "aws_region" "current" {}
data "aws_caller_identity" "current" {}

# Local values
locals {
  cluster_name = data.terraform_remote_state.base.outputs.cluster_name
  common_tags = merge(
    data.terraform_remote_state.base.outputs.common_tags,
    {
      Layer = "application"
    },
    var.additional_tags
  )
  cluster_oidc_host        = replace(data.terraform_remote_state.base.outputs.cluster_oidc_issuer_url, "https://", "")
  eso_role_name            = split("/", data.terraform_remote_state.middleware.outputs.eso_role_arn)[1]
  ado_secret_name          = data.terraform_remote_state.middleware.outputs.ado_secret_name
  ado_external_secret_name = "${local.ado_secret_name}-secret"
  ado_agent_auth_mode      = lower(var.ado_agent_auth_mode)
  ado_agent_spn_enabled    = local.ado_agent_auth_mode == "spn"
  ado_agent_spn_aws_secret_name = (
    var.ado_agent_spn_secret.aws_secret_name != null
    ? trimspace(var.ado_agent_spn_secret.aws_secret_name)
    : ""
  )
  ado_agent_spn_secret_name = (
    var.ado_agent_spn_secret.k8s_secret_name != null && trimspace(var.ado_agent_spn_secret.k8s_secret_name) != ""
    ? trimspace(var.ado_agent_spn_secret.k8s_secret_name)
    : "ado-agent-spn"
  )
  ado_agent_spn_refresh_interval = (
    var.ado_agent_spn_secret.refresh_interval != null && trimspace(var.ado_agent_spn_secret.refresh_interval) != ""
    ? trimspace(var.ado_agent_spn_secret.refresh_interval)
    : var.secret_refresh_interval
  )
  ado_agent_spn_external_secret_name = "${local.ado_agent_spn_secret_name}-secret"
  requires_ado_pat_secret = anytrue([
    for pool in values(var.agent_pools) : pool.enabled
  ])

  ado_execution_policy_statements = {
    for role_key, role_cfg in var.ado_execution_roles :
    role_key => {
      for idx, permission in role_cfg.permissions :
      format("stmt_%02d", idx + 1) => (
        permission.effect == "Allow"
        ? merge(
          {
            sid = format(
              "Allow%s%02d",
              replace(replace(upper(role_key), "-", ""), "_", ""),
              idx + 1
            )
            actions   = permission.actions
            resources = permission.resources
          },
          permission.condition == null
          ? {}
          : {
            conditions = [
              {
                test     = permission.condition.test
                variable = permission.condition.variable
                values   = permission.condition.values
              }
            ]
          }
        )
        : error(
          "ADO execution role \"${role_key}\" permission index ${idx} uses effect \"${permission.effect}\".",
          "The primitive IAM policy module only supports Allow statements."
        )
      )
    }
  }
}

data "aws_secretsmanager_secret" "ado_agent_spn" {
  count = local.ado_agent_spn_enabled && local.ado_agent_spn_aws_secret_name != "" ? 1 : 0
  name  = local.ado_agent_spn_aws_secret_name
}

# ECR Repositories for ADO agent images
module "ecr" {
  count  = length(var.ecr_repositories) > 0 ? 1 : 0
  source = "./modules/collections/ecr"

  ecr_repositories       = local.ecr_repositories_with_defaults
  cluster_name           = local.cluster_name
  create_iam_policies    = true
  attach_pull_to_fargate = true
  fargate_role_name      = data.terraform_remote_state.base.outputs.fargate_role_name
  attach_bastion_policy  = false # No bastion in this architecture
  bastion_role_name      = ""

  tags = local.common_tags
}

# AWS Secrets Manager secret for ADO PAT
resource "aws_secretsmanager_secret" "ado_pat" {
  # checkov:skip=CKV2_AWS_57:ADO Personal Access Token rotation is managed externally in Azure DevOps, not through AWS Secrets Manager rotation
  name                    = var.ado_pat_secret_name
  description             = "Personal Access Token for Azure DevOps integration"
  recovery_window_in_days = var.secret_recovery_days
  kms_key_id              = data.terraform_remote_state.base.outputs.kms_key_arn

  tags = merge(
    local.common_tags,
    {
      Purpose    = "ADO-Integration"
      ManagedBy  = "terraform"
      SecretType = "ado-agent-pat"
    }
  )
}

resource "aws_secretsmanager_secret_version" "ado_pat" {
  secret_id = aws_secretsmanager_secret.ado_pat.id
  secret_string = jsonencode({
    personalAccessToken = var.ado_pat_value
    organization        = var.ado_org
    adourl              = var.ado_url
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}

# Bootstrap the Kubernetes PAT secret before Helm creates placeholder/jobs that mount it.
# ESO refreshes the same secret from AWS Secrets Manager after the ExternalSecret reconciles.
resource "kubernetes_secret" "ado_pat_bootstrap" {
  count = local.requires_ado_pat_secret ? 1 : 0

  metadata {
    name      = local.ado_secret_name
    namespace = data.terraform_remote_state.middleware.outputs.ado_agents_namespace
    labels = {
      "app.kubernetes.io/name"       = "ado-agent-cluster"
      "app.kubernetes.io/component"  = "ado-agent-pat"
      "app.kubernetes.io/managed-by" = "terraform"
    }
  }

  type = "Opaque"

  data = {
    personalAccessToken = var.ado_pat_value
    organization        = var.ado_org
    adourl              = var.ado_url
  }

  depends_on = [
    aws_secretsmanager_secret_version.ado_pat
  ]

  lifecycle {
    ignore_changes = [
      data,
      metadata[0].annotations,
      metadata[0].labels
    ]
  }
}

resource "terraform_data" "agent_pool_image_repository_validation" {
  input = length(var.ecr_repositories)

  lifecycle {
    precondition {
      condition = length(var.ecr_repositories) > 0 || alltrue([
        for pool_config in values(var.agent_pools) :
        !pool_config.enabled || trimspace(pool_config.image_repository) != ""
      ])
      error_message = "Each enabled agent pool must set image_repository when ecr_repositories is empty."
    }
  }
}

resource "terraform_data" "ado_agent_auth_validation" {
  input = local.ado_agent_auth_mode

  lifecycle {
    precondition {
      condition     = !local.ado_agent_spn_enabled || local.ado_agent_spn_aws_secret_name != ""
      error_message = "ado_agent_spn_secret.aws_secret_name is required when ado_agent_auth_mode is \"spn\"."
    }
  }
}

# ADO Agent Execution Roles (IRSA)
module "ado_agent_execution_role" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  for_each = var.ado_execution_roles
  source   = "terraform.registry.launch.nttdata.com/module_primitive/iam_role/aws"
  version  = "~> 0.1"

  name = "${local.cluster_name}-ado-agent-${each.key}-role"

  assume_role_policy = [
    {
      actions = ["sts:AssumeRoleWithWebIdentity"]
      principals = [
        {
          type        = "Federated"
          identifiers = [data.terraform_remote_state.base.outputs.oidc_provider_arn]
        }
      ]
      conditions = [
        {
          test     = "StringEquals"
          variable = "${local.cluster_oidc_host}:sub"
          values = [
            "system:serviceaccount:${each.value.namespace}:${each.value.service_account_name}"
          ]
        },
        {
          test     = "StringEquals"
          variable = "${local.cluster_oidc_host}:aud"
          values   = ["sts.amazonaws.com"]
        }
      ]
    }
  ]

  tags = merge(local.common_tags, {
    Role      = "ADO-Agent-${title(each.key)}"
    Component = "ado-agent"
  })
}

# Managed policies for ADO agent execution roles
module "ado_agent_execution_policy" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  for_each = var.ado_execution_roles
  source   = "terraform.registry.launch.nttdata.com/module_primitive/iam_policy/aws"
  version  = "~> 0.1"

  policy_name      = "${local.cluster_name}-ado-agent-${each.key}-policy"
  policy_statement = local.ado_execution_policy_statements[each.key]

  tags = merge(local.common_tags, {
    Role      = "ADO-Agent-${title(each.key)}"
    Component = "ado-agent"
  })
}

module "ado_agent_execution_policy_attachment" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  for_each = var.ado_execution_roles
  source   = "terraform.registry.launch.nttdata.com/module_primitive/iam_role_policy_attachment/aws"
  version  = "~> 0.1"

  role_name  = module.ado_agent_execution_role[each.key].role_name
  policy_arn = module.ado_agent_execution_policy[each.key].policy_arn
}

# Grant ESO access to ADO PAT secret via managed policy
module "eso_ado_secret_access_policy" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_policy/aws"
  version = "~> 0.1"

  policy_name = "${local.cluster_name}-eso-ado-secret-access"

  policy_statement = {
    secret_access = {
      sid = "AllowAdoPatSecretAccess"
      actions = [
        "secretsmanager:GetSecretValue",
        "secretsmanager:DescribeSecret"
      ]
      resources = concat(
        [aws_secretsmanager_secret.ado_pat.arn],
        length(data.aws_secretsmanager_secret.ado_agent_spn) > 0 ? [data.aws_secretsmanager_secret.ado_agent_spn[0].arn] : []
      )
    }
  }

  tags = local.common_tags
}

module "eso_ado_secret_access_policy_attachment" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role_policy_attachment/aws"
  version = "~> 0.1"

  role_name  = local.eso_role_name
  policy_arn = module.eso_ado_secret_access_policy.policy_arn
}

resource "terraform_data" "wait_for_ado_agent_spn_secret" {
  count = local.ado_agent_spn_enabled ? 1 : 0

  triggers_replace = {
    cluster_name         = local.cluster_name
    region               = data.aws_region.current.name
    namespace            = data.terraform_remote_state.middleware.outputs.ado_agents_namespace
    spn_secret_name      = local.ado_agent_spn_secret_name
    external_secret_name = local.ado_agent_spn_external_secret_name
    aws_secret_name      = local.ado_agent_spn_aws_secret_name
  }

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -euo pipefail

      aws eks update-kubeconfig \
        --alias '${local.cluster_name}' \
        --name '${local.cluster_name}' \
        --region '${data.aws_region.current.name}' >/dev/null

      kubectl apply --context '${local.cluster_name}' -f - <<'YAML'
      apiVersion: external-secrets.io/v1
      kind: ClusterSecretStore
      metadata:
        name: ${data.terraform_remote_state.middleware.outputs.cluster_secret_store_name}
      spec:
        provider:
          aws:
            service: SecretsManager
            region: ${data.aws_region.current.name}
            auth:
              jwt:
                serviceAccountRef:
                  name: ${data.terraform_remote_state.middleware.outputs.eso_service_account_name}
                  namespace: ${data.terraform_remote_state.middleware.outputs.eso_namespace}
      YAML

      for _ in $(seq 1 30); do
        store_status="$(kubectl get clustersecretstore '${data.terraform_remote_state.middleware.outputs.cluster_secret_store_name}' \
          --context '${local.cluster_name}' \
          -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}' 2>/dev/null || true)"
        if [ "$store_status" = "True" ]; then
          break
        fi
        sleep 2
      done

      store_status="$(kubectl get clustersecretstore '${data.terraform_remote_state.middleware.outputs.cluster_secret_store_name}' \
        --context '${local.cluster_name}' \
        -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}' 2>/dev/null || true)"
      if [ "$store_status" != "True" ]; then
        echo "Timed out waiting for ClusterSecretStore '${data.terraform_remote_state.middleware.outputs.cluster_secret_store_name}' to become Ready." >&2
        kubectl get clustersecretstore '${data.terraform_remote_state.middleware.outputs.cluster_secret_store_name}' \
          --context '${local.cluster_name}' \
          -o yaml >&2 || true
        exit 1
      fi

      secret_json="$(aws secretsmanager get-secret-value \
        --secret-id '${local.ado_agent_spn_aws_secret_name}' \
        --region '${data.aws_region.current.name}' \
        --query SecretString \
        --output text)"

      if ! jq -e '
        type == "object"
        and (.ClientId | type == "string" and length > 0)
        and (.ClientSecret | type == "string" and length > 0)
        and (.TenantId | type == "string" and length > 0)
      ' >/dev/null <<< "$secret_json"; then
        echo "SPN secret '${local.ado_agent_spn_aws_secret_name}' must be readable and contain non-empty ClientId, ClientSecret, and TenantId string properties." >&2
        exit 1
      fi

      kubectl apply --context '${local.cluster_name}' -f - <<'YAML'
      apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      metadata:
        name: ${local.ado_agent_spn_external_secret_name}
        namespace: ${data.terraform_remote_state.middleware.outputs.ado_agents_namespace}
        labels:
          app.kubernetes.io/managed-by: terraform
          app.kubernetes.io/component: ado-agent-spn
          app.kubernetes.io/name: ado-agent-cluster
      spec:
        refreshInterval: ${local.ado_agent_spn_refresh_interval}
        secretStoreRef:
          name: ${data.terraform_remote_state.middleware.outputs.cluster_secret_store_name}
          kind: ClusterSecretStore
        target:
          name: ${local.ado_agent_spn_secret_name}
          creationPolicy: Owner
          template:
            type: Opaque
        data:
        - secretKey: AZP_CLIENTID
          remoteRef:
            key: ${local.ado_agent_spn_aws_secret_name}
            property: ClientId
        - secretKey: AZP_CLIENTSECRET
          remoteRef:
            key: ${local.ado_agent_spn_aws_secret_name}
            property: ClientSecret
        - secretKey: AZP_TENANTID
          remoteRef:
            key: ${local.ado_agent_spn_aws_secret_name}
            property: TenantId
      YAML

      for _ in $(seq 1 60); do
        if kubectl get secret '${local.ado_agent_spn_secret_name}' \
          --namespace '${data.terraform_remote_state.middleware.outputs.ado_agents_namespace}' \
          --context '${local.cluster_name}' \
          -o jsonpath='{.data.AZP_CLIENTID}{"\n"}{.data.AZP_CLIENTSECRET}{"\n"}{.data.AZP_TENANTID}' 2>/dev/null |
          awk 'NF { count++ } END { exit count == 3 ? 0 : 1 }'; then
          exit 0
        fi
        sleep 5
      done

      echo "Timed out waiting for SPN secret '${local.ado_agent_spn_secret_name}' in namespace '${data.terraform_remote_state.middleware.outputs.ado_agents_namespace}'." >&2
      kubectl get externalsecret '${local.ado_agent_spn_external_secret_name}' \
        --namespace '${data.terraform_remote_state.middleware.outputs.ado_agents_namespace}' \
        --context '${local.cluster_name}' \
        -o yaml >&2 || true
      exit 1
    EOT
  }

  provisioner "local-exec" {
    when        = destroy
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -euo pipefail

      aws eks update-kubeconfig \
        --alias '${self.triggers_replace.cluster_name}' \
        --name '${self.triggers_replace.cluster_name}' \
        --region '${self.triggers_replace.region}' >/dev/null || exit 0

      if ! kubectl get namespace '${self.triggers_replace.namespace}' \
        --context '${self.triggers_replace.cluster_name}' >/dev/null 2>&1; then
        exit 0
      fi

      if ! kubectl get externalsecret '${self.triggers_replace.external_secret_name}' \
        --namespace '${self.triggers_replace.namespace}' \
        --context '${self.triggers_replace.cluster_name}' >/dev/null 2>&1; then
        exit 0
      fi

      kubectl delete externalsecret '${self.triggers_replace.external_secret_name}' \
        --namespace '${self.triggers_replace.namespace}' \
        --context '${self.triggers_replace.cluster_name}' \
        --wait=false \
        --ignore-not-found=true || true

      for _ in $(seq 1 30); do
        if ! kubectl get externalsecret '${self.triggers_replace.external_secret_name}' \
          --namespace '${self.triggers_replace.namespace}' \
          --context '${self.triggers_replace.cluster_name}' >/dev/null 2>&1; then
          exit 0
        fi
        sleep 2
      done

      kubectl patch externalsecret '${self.triggers_replace.external_secret_name}' \
        --namespace '${self.triggers_replace.namespace}' \
        --context '${self.triggers_replace.cluster_name}' \
        --type=merge \
        -p '{"metadata":{"finalizers":null}}' || true

      kubectl delete externalsecret '${self.triggers_replace.external_secret_name}' \
        --namespace '${self.triggers_replace.namespace}' \
        --context '${self.triggers_replace.cluster_name}' \
        --wait=false \
        --ignore-not-found=true || true
    EOT
  }

  depends_on = [
    module.eso_ado_secret_access_policy_attachment,
    terraform_data.ado_agent_auth_validation
  ]
}

# Prepare Helm values for ADO agent deployment
locals {
  helm_values = {
    global = {
      namespace   = data.terraform_remote_state.middleware.outputs.ado_agents_namespace
      clusterName = local.cluster_name
      region      = data.aws_region.current.name
    }

    # Disable all default agent pools from values.yaml
    # We only want the pools we explicitly define here
    agentPools = merge(
      {
        # Disable the default dev-build pool from values.yaml
        dev-build = {
          enabled = false
        }
        iac = {
          enabled = false
        }
      },
      {
        for pool_name, pool_config in local.agent_pools_with_region : pool_name => {
          enabled = pool_config.enabled
          name    = pool_name

          ado = {
            poolName   = pool_config.ado_pool_name
            secretName = local.ado_secret_name
          }

          image = {
            repository = length(var.ecr_repositories) > 0 ? module.ecr[0].repository_urls[pool_config.ecr_repository_key] : pool_config.image_repository
            tag        = pool_config.image_tag
            pullPolicy = pool_config.image_pull_policy
          }

          serviceAccount = {
            name    = pool_config.service_account_name
            roleArn = module.ado_agent_execution_role[pool_name].role_arn
          }

          resources = pool_config.resources

          autoscaling = {
            enabled                              = pool_config.autoscaling.enabled
            maxReplicas                          = pool_config.autoscaling.max_replicas
            pollingInterval                      = pool_config.autoscaling.polling_interval
            targetPipelinesQueueLength           = pool_config.autoscaling.target_queue_length
            activationTargetPipelinesQueueLength = pool_config.autoscaling.activation_target_queue_length
            jobsToFetch                          = pool_config.autoscaling.jobs_to_fetch
            fetchUnfinishedJobsOnly              = pool_config.autoscaling.fetch_unfinished_jobs_only
            poolID                               = pool_config.autoscaling.pool_id
            templateAgentName                    = pool_config.autoscaling.template_agent_name != "" ? pool_config.autoscaling.template_agent_name : (pool_config.autoscaling.create_template_agent ? "${pool_name}-keda-template" : "")
            createTemplateAgent                  = pool_config.autoscaling.create_template_agent
            placeholderBackoffLimit              = pool_config.autoscaling.placeholder_backoff_limit
            placeholderTtlSecondsAfterFinished   = pool_config.autoscaling.placeholder_ttl_seconds_after_finished
            demands                              = pool_config.autoscaling.demands
            requireAllDemands                    = pool_config.autoscaling.require_all_demands
            requireAllDemandsAndIgnoreOthers     = pool_config.autoscaling.require_all_demands_and_ignore_others
            caseInsensitiveDemandsProcessing     = pool_config.autoscaling.case_insensitive_demands_processing
            backoffLimit                         = pool_config.autoscaling.backoff_limit
            ttlSecondsAfterFinished              = pool_config.autoscaling.ttl_seconds_after_finished
            successfulJobsHistoryLimit           = pool_config.autoscaling.successful_jobs_history_limit
            failedJobsHistoryLimit               = pool_config.autoscaling.failed_jobs_history_limit
          }

          tolerations               = pool_config.tolerations
          nodeSelector              = pool_config.node_selector
          affinity                  = pool_config.affinity
          topologySpreadConstraints = pool_config.topology_spread_constraints

          # Additional environment variables
          env = pool_config.additional_env_vars

          # Volume mounts and volumes
          volumeMounts = pool_config.volume_mounts
          volumes      = pool_config.volumes
        }
      }
    )

    auth = {
      mode          = local.ado_agent_auth_mode
      spnSecretName = local.ado_agent_spn_secret_name
    }

    externalSecrets = {
      enabled                = true
      clusterSecretStoreName = data.terraform_remote_state.middleware.outputs.cluster_secret_store_name
      secrets = {
        "${local.ado_external_secret_name}" = {
          aws = {
            secretName = aws_secretsmanager_secret.ado_pat.name
            region     = data.aws_region.current.name
          }
          k8s = {
            secretName      = local.ado_secret_name
            type            = "Opaque"
            refreshInterval = var.secret_refresh_interval
            creationPolicy  = "Merge"
          }
          data = {
            personalAccessToken = "personalAccessToken"
            organization        = "organization"
            adourl              = "adourl"
          }
        }
      }
    }

    buildkit = {
      enabled  = data.terraform_remote_state.middleware.outputs.buildkitd_enabled
      endpoint = data.terraform_remote_state.middleware.outputs.buildkitd_service_endpoint
    }

    agent = {
      runOnce                       = var.agent_run_once
      recyclePodAfterRunOnce        = var.agent_recycle_pod_after_run_once
      cleanupTimeoutSeconds         = var.agent_cleanup_timeout_seconds
      terminationGracePeriodSeconds = var.agent_termination_grace_period_seconds
      automountServiceAccountToken  = var.agent_automount_service_account_token
    }

    # Common labels and annotations
    commonLabels = var.common_labels
    labels       = var.additional_labels
    annotations  = var.additional_annotations

    # Security contexts
    podSecurityContext = var.pod_security_context
    securityContext    = var.container_security_context
  }
}

# Deploy ADO agents via Helm
resource "helm_release" "ado_agents" {
  name       = "ado-agents"
  repository = "${path.module}/helm"
  chart      = "ado-agent-cluster"
  namespace  = data.terraform_remote_state.middleware.outputs.ado_agents_namespace

  values = [yamlencode(local.helm_values)]

  # Ensure dependencies are ready
  depends_on = [
    aws_secretsmanager_secret_version.ado_pat,
    kubernetes_secret.ado_pat_bootstrap,
    terraform_data.agent_pool_image_repository_validation,
    terraform_data.ado_agent_auth_validation,
    terraform_data.wait_for_ado_agent_spn_secret,
    module.ado_agent_execution_policy_attachment,
    module.eso_ado_secret_access_policy_attachment
  ]

  # Wait for resources to be ready
  wait          = true
  wait_for_jobs = false
  timeout       = 600

  # Default to preserving failed hook jobs/pods so deployment failures can be
  # inspected. Environments can opt back into rollback cleanup after validation.
  atomic            = var.ado_agents_helm_atomic
  cleanup_on_fail   = var.ado_agents_helm_cleanup_on_fail
  disable_crd_hooks = false
  # KEDA and ESO CRDs are installed by the middleware layer. Discovery can lag briefly
  # after CRD creation, so avoid failing the release on stale local OpenAPI data.
  disable_openapi_validation = true
  disable_webhooks           = false
  force_update               = false
  recreate_pods              = false
  reset_values               = false
  reuse_values               = false
  skip_crds                  = false

  # Set resource limits for Helm operations
  max_history = 10
}
