# Application Layer - ADO Agents and Application Resources
#
# This layer deploys application-specific resources:
# - ECR repositories for agent container images
# - AWS Secrets Manager secrets for ADO integration
# - Helm chart deployment for ADO agents
# - IAM roles for agent execution (IRSA)
#
# This layer depends on both base infrastructure and middleware layers.

# Note: Backend and provider configurations are generated by Terragrunt
# See: terragrunt.hcl and root terragrunt.hcl
# Kubernetes and Helm providers are configured in k8s_provider_generated.tf

# Data sources
data "aws_region" "current" {}
data "aws_caller_identity" "current" {}

# Local values
locals {
  cluster_name = data.terraform_remote_state.base.outputs.cluster_name
  common_tags = merge(
    data.terraform_remote_state.base.outputs.common_tags,
    {
      Layer = "application"
    },
    var.additional_tags
  )
  cluster_oidc_host = replace(data.terraform_remote_state.base.outputs.cluster_oidc_issuer_url, "https://", "")
  eso_role_name     = split("/", data.terraform_remote_state.middleware.outputs.eso_role_arn)[1]

  ado_execution_policy_statements = {
    for role_key, role_cfg in var.ado_execution_roles :
    role_key => {
      for idx, permission in role_cfg.permissions :
      format("stmt_%02d", idx + 1) => (
        permission.effect == "Allow"
        ? merge(
          {
            sid = format(
              "Allow%s%02d",
              replace(replace(upper(role_key), "-", ""), "_", ""),
              idx + 1
            )
            actions   = permission.actions
            resources = permission.resources
          },
          permission.condition == null
          ? {}
          : {
            conditions = [
              {
                test     = permission.condition.test
                variable = permission.condition.variable
                values   = permission.condition.values
              }
            ]
          }
        )
        : error(
          "ADO execution role \"${role_key}\" permission index ${idx} uses effect \"${permission.effect}\".",
          "The primitive IAM policy module only supports Allow statements."
        )
      )
    }
  }
}

# ECR Repositories for ADO agent images
module "ecr" {
  count  = length(var.ecr_repositories) > 0 ? 1 : 0
  source = "./modules/collections/ecr"

  ecr_repositories       = local.ecr_repositories_with_defaults
  cluster_name           = local.cluster_name
  create_iam_policies    = true
  attach_pull_to_fargate = true
  fargate_role_name      = data.terraform_remote_state.base.outputs.fargate_role_name
  attach_bastion_policy  = false # No bastion in this architecture
  bastion_role_name      = ""

  tags = local.common_tags
}

# AWS Secrets Manager secret for ADO PAT
resource "aws_secretsmanager_secret" "ado_pat" {
  # checkov:skip=CKV2_AWS_57:ADO Personal Access Token rotation is managed externally in Azure DevOps, not through AWS Secrets Manager rotation
  name                    = var.ado_pat_secret_name
  description             = "Personal Access Token for Azure DevOps integration"
  recovery_window_in_days = var.secret_recovery_days
  kms_key_id              = data.terraform_remote_state.base.outputs.kms_key_arn

  tags = merge(
    local.common_tags,
    {
      Purpose    = "ADO-Integration"
      ManagedBy  = "terraform"
  SecretType = "ado-agent-pat"
    }
  )
}

resource "aws_secretsmanager_secret_version" "ado_pat" {
  secret_id = aws_secretsmanager_secret.ado_pat.id
  secret_string = jsonencode({
    personalAccessToken = var.ado_pat_value
    organization        = var.ado_org
    adourl              = var.ado_url
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}

# ADO Agent Execution Roles (IRSA)
module "ado_agent_execution_role" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  for_each = var.ado_execution_roles
  source   = "terraform.registry.launch.nttdata.com/module_primitive/iam_role/aws"
  version  = "~> 0.1"

  name = "${local.cluster_name}-ado-agent-${each.key}-role"

  assume_role_policy = [
    {
      actions = ["sts:AssumeRoleWithWebIdentity"]
      principals = [
        {
          type        = "Federated"
          identifiers = [data.terraform_remote_state.base.outputs.oidc_provider_arn]
        }
      ]
      conditions = [
        {
          test     = "StringEquals"
          variable = "${local.cluster_oidc_host}:sub"
          values = [
            "system:serviceaccount:${each.value.namespace}:${each.value.service_account_name}"
          ]
        },
        {
          test     = "StringEquals"
          variable = "${local.cluster_oidc_host}:aud"
          values   = ["sts.amazonaws.com"]
        }
      ]
    }
  ]

  tags = merge(local.common_tags, {
    Role      = "ADO-Agent-${title(each.key)}"
    Component = "ado-agent"
  })
}

# Managed policies for ADO agent execution roles
module "ado_agent_execution_policy" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  for_each = var.ado_execution_roles
  source   = "terraform.registry.launch.nttdata.com/module_primitive/iam_policy/aws"
  version  = "~> 0.1"

  policy_name      = "${local.cluster_name}-ado-agent-${each.key}-policy"
  policy_statement = local.ado_execution_policy_statements[each.key]

  tags = merge(local.common_tags, {
    Role      = "ADO-Agent-${title(each.key)}"
    Component = "ado-agent"
  })
}

module "ado_agent_execution_policy_attachment" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  for_each = var.ado_execution_roles
  source   = "terraform.registry.launch.nttdata.com/module_primitive/iam_role_policy_attachment/aws"
  version  = "~> 0.1"

  role_name  = module.ado_agent_execution_role[each.key].role_name
  policy_arn = module.ado_agent_execution_policy[each.key].policy_arn
}

# Grant ESO access to ADO PAT secret via managed policy
module "eso_ado_secret_access_policy" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_policy/aws"
  version = "~> 0.1"

  policy_name = "${local.cluster_name}-eso-ado-secret-access"

  policy_statement = {
    secret_access = {
      sid = "AllowAdoPatSecretAccess"
      actions = [
        "secretsmanager:GetSecretValue",
        "secretsmanager:DescribeSecret"
      ]
      resources = [aws_secretsmanager_secret.ado_pat.arn]
    }
  }

  tags = local.common_tags
}

module "eso_ado_secret_access_policy_attachment" {
  # checkov:skip=CKV_TF_1: module source is trusted internal registry
  source  = "terraform.registry.launch.nttdata.com/module_primitive/iam_role_policy_attachment/aws"
  version = "~> 0.1"

  role_name  = local.eso_role_name
  policy_arn = module.eso_ado_secret_access_policy.policy_arn
}

# Prepare Helm values for ADO agent deployment
locals {
  ado_secret_name          = data.terraform_remote_state.middleware.outputs.ado_secret_name
  ado_external_secret_name = "${local.ado_secret_name}-secret"

  helm_values = {
    global = {
      namespace   = data.terraform_remote_state.middleware.outputs.ado_agents_namespace
      clusterName = local.cluster_name
      region      = data.aws_region.current.name
    }

    # Disable all default agent pools from values.yaml
    # We only want the pools we explicitly define here
    agentPools = merge(
      {
        # Disable the default dev-build pool from values.yaml
        dev-build = {
          enabled = false
        }
        iac = {
          enabled = false
        }
      },
      {
        for pool_name, pool_config in local.agent_pools_with_region : pool_name => {
          enabled = pool_config.enabled
          name    = pool_name

          ado = {
            poolName   = pool_config.ado_pool_name
            secretName = local.ado_secret_name
          }

          image = {
            repository = length(var.ecr_repositories) > 0 ? module.ecr[0].repository_urls[pool_config.ecr_repository_key] : pool_config.image_repository
            tag        = pool_config.image_tag
            pullPolicy = pool_config.image_pull_policy
          }

          serviceAccount = {
            name    = pool_config.service_account_name
            roleArn = module.ado_agent_execution_role[pool_name].role_arn
          }

          resources = pool_config.resources

          autoscaling = {
            enabled                    = pool_config.autoscaling.enabled
            minReplicas                = pool_config.autoscaling.min_replicas
            maxReplicas                = pool_config.autoscaling.max_replicas
            targetPipelinesQueueLength = pool_config.autoscaling.target_queue_length
          }

          tolerations  = pool_config.tolerations
          nodeSelector = pool_config.node_selector
          affinity     = pool_config.affinity

          # Additional environment variables
          env = pool_config.additional_env_vars

          # Volume mounts and volumes
          volumeMounts = pool_config.volume_mounts
          volumes      = pool_config.volumes
        }
      }
    )

    externalSecrets = {
      enabled                = true
      clusterSecretStoreName = data.terraform_remote_state.middleware.outputs.cluster_secret_store_name
      secrets = {
        "${local.ado_external_secret_name}" = {
          aws = {
            secretName = aws_secretsmanager_secret.ado_pat.name
            region     = data.aws_region.current.name
          }
          k8s = {
            secretName      = local.ado_secret_name
            type            = "Opaque"
            refreshInterval = var.secret_refresh_interval
          }
          data = {
            personalAccessToken = "personalAccessToken"
            organization        = "organization"
            adourl              = "adourl"
          }
        }
      }
    }

    buildkit = {
      enabled  = data.terraform_remote_state.middleware.outputs.buildkitd_enabled
      endpoint = data.terraform_remote_state.middleware.outputs.buildkitd_service_endpoint
    }

    # Common labels and annotations
    commonLabels = var.common_labels
    labels       = var.additional_labels
    annotations  = var.additional_annotations

    # Security contexts
    podSecurityContext = var.pod_security_context
    securityContext    = var.container_security_context
  }
}

# Deploy ADO agents via Helm
resource "helm_release" "ado_agents" {
  name       = "ado-agents"
  repository = "${path.module}/helm"
  chart      = "ado-agent-cluster"
  namespace  = data.terraform_remote_state.middleware.outputs.ado_agents_namespace

  values = [yamlencode(local.helm_values)]

  # Ensure dependencies are ready
  depends_on = [
    aws_secretsmanager_secret_version.ado_pat,
    module.ado_agent_execution_policy_attachment,
    module.eso_ado_secret_access_policy_attachment
  ]

  # Wait for resources to be ready
  wait          = true
  wait_for_jobs = false
  timeout       = 600

  # Enable atomic operations for safe upgrades
  atomic            = true
  cleanup_on_fail   = true
  disable_crd_hooks = false
  disable_webhooks  = false
  force_update      = false
  recreate_pods     = false
  reset_values      = false
  reuse_values      = false
  skip_crds         = false

  # Set resource limits for Helm operations
  max_history = 10
}