{{- range $poolName, $poolConfig := .Values.agentPools }}
{{- if $poolConfig.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ado-agent-cluster.serviceAccountName" (dict "serviceAccount" $poolConfig.serviceAccount "poolName" $poolName) }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "ado-agent-cluster.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $poolName }}
  {{- with $.Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $poolConfig.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $poolConfig.serviceAccount.roleArn | quote }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
{{- end }}